// Game entries for ServerplexOS Games app
// Source: ChiliBowlFlash (CBGamesdev/chilibowlflash)
// CDN: cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/

var CHILIBOWL_GAMES = [
  {
    id: 'cb-slope',
    name: 'Slope',
    icon: '⛷️',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/slope/index.html',
    category: 'Arcade',
    author: 'Rob Kay',
    description: 'Control a ball rolling down a steep slope. Dodge obstacles at breakneck speed as the track gets faster and more unpredictable.',
    featured: true,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-run3',
    name: 'Run 3',
    icon: '🏃',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/run3/index.html',
    category: 'Arcade',
    author: 'Player 03',
    description: 'Run, skate, and jump through an endless series of tunnels in space. Choose your character and avoid falling into the void.',
    featured: true,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-retrobowl',
    name: 'Retro Bowl',
    icon: '🏈',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/retrobowl/index.html',
    category: 'Sports',
    author: 'New Star Games',
    description: 'Manage and play as an American football team in this retro-styled gridiron game. Draft players, call plays, and lead your team to the championship.',
    featured: true,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-retrobowl-college',
    name: 'Retro Bowl College',
    icon: '🏈',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/retrobowlcollege/index.html',
    category: 'Sports',
    author: 'New Star Games',
    description: 'The college football edition of Retro Bowl. Build your program, recruit players, and compete for the national title.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-geodash',
    name: 'Geometry Dash',
    icon: '🔷',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/geodash/index.html',
    category: 'Arcade',
    author: 'RobTop Games',
    description: 'Jump and fly your way through danger in this rhythm-based action platformer. One touch controls, tight gameplay, and a killer soundtrack.',
    featured: true,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-1v1-lol',
    name: '1v1.LOL',
    icon: '🔫',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/1v1/index.html',
    category: 'Multiplayer',
    author: '1v1.LOL',
    description: 'Build, edit, and fight in this online multiplayer shooter. Practice your building and shooting mechanics against real players.',
    featured: true,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-2048',
    name: '2048',
    icon: '🔢',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/2048/index.html',
    category: 'Puzzle',
    author: 'Gabriele Cirulli',
    description: 'Slide numbered tiles on a grid to combine them. Reach the 2048 tile — but the game does not have to end there.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-motox3m',
    name: 'Moto X3M',
    icon: '🏍️',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/motox3m/index.html',
    category: 'Racing',
    author: 'Madpuffers',
    description: 'Race your motorbike through insane obstacle courses. Perform flips to shave time and unlock new bikes.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-motox3m2',
    name: 'Moto X3M 2',
    icon: '🏍️',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/motox3m2/index.html',
    category: 'Racing',
    author: 'Madpuffers',
    description: 'More levels, more insane stunts, and more explosive obstacles in the sequel to the smash-hit bike racer.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-google-dino',
    name: 'Google Dino',
    icon: '🦕',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/googdino/index.html',
    category: 'Arcade',
    author: 'Google',
    description: 'The classic Chrome offline dinosaur runner. Jump over cacti and duck under pterodactyls. How far can you get?',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-google-snake',
    name: 'Google Snake',
    icon: '🐍',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/googsnake/index.html',
    category: 'Arcade',
    author: 'Google',
    description: 'Google\'s version of the classic Snake game with multiple maps, modes, and food types to unlock.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-mario',
    name: 'Super Mario Bros',
    icon: '🍄',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/mario/index.html',
    category: 'Platformer',
    author: 'Nintendo (fan port)',
    description: 'The iconic Super Mario Bros platformer running in your browser. Jump on Goombas, grab mushrooms, and rescue Princess Peach.',
    featured: true,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-sm64',
    name: 'Super Mario 64',
    icon: '⭐',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/sm64/index.html',
    category: 'Platformer',
    author: 'Nintendo (fan port)',
    description: 'The legendary Nintendo 64 classic playable in your browser. Collect stars, explore Peach\'s castle, and defeat Bowser.',
    featured: true,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-happywheels',
    name: 'Happy Wheels',
    icon: '🩸',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/hw/index.html',
    category: 'Arcade',
    author: 'Jim Bonacci',
    description: 'A ragdoll physics platformer with absurdly gory levels. Choose a character and try to reach the finish line in one piece.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-bloxorz',
    name: 'Bloxorz',
    icon: '📦',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/bloxorz.html',
    category: 'Puzzle',
    author: 'Damian Clarke',
    description: 'Roll a block across suspended platforms and drop it into the square hole. One wrong move and you fall off the edge.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-bloons',
    name: 'Bloons Tower Defense',
    icon: '🎈',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/bloons.html',
    category: 'Strategy',
    author: 'Ninja Kiwi',
    description: 'Place monkey towers to pop waves of balloons before they escape. The original flash classic that spawned a massive franchise.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-pacman',
    name: 'Pac-Man',
    icon: '👾',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/Pacman.html',
    category: 'Arcade',
    author: 'Namco',
    description: 'The arcade classic. Eat all the dots while avoiding ghosts, and use power pellets to turn the tables.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-ageofwar',
    name: 'Age of War',
    icon: '⚔️',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/ageofwar.html',
    category: 'Strategy',
    author: 'Louissi',
    description: 'Evolve your civilization from cavemen to futuristic soldiers. Deploy units and defend your base while attacking the enemy.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-bubble',
    name: 'Bubble Shooter',
    icon: '🔵',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/bubble.html',
    category: 'Arcade',
    author: 'ChiliBowl',
    description: 'Aim and shoot colored bubbles to form groups of 3 or more and clear the board before bubbles reach the bottom.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-tomb-of-mask',
    name: 'Tomb of the Mask',
    icon: '💀',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/totm/index.html',
    category: 'Arcade',
    author: 'Playgendary',
    description: 'Slide through an endless procedurally generated vertical maze. Collect dots, dodge traps, and climb as high as you can.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-blockblast',
    name: 'Block Blast',
    icon: '🟦',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/blockblast/index.html',
    category: 'Puzzle',
    author: 'Hungry Studio',
    description: 'Place blocks on a grid to clear full rows and columns. Simple to learn but endlessly satisfying to master.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-basketball-stars',
    name: 'Basketball Stars',
    icon: '🏀',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/bstars/index.html',
    category: 'Sports',
    author: 'Miniclip',
    description: '1v1 basketball against players worldwide. Perform dribbles, dunks, and trick shots to outplay your opponent.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-wolfen',
    name: 'Wolfenstein 3D',
    icon: '🔫',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/wolfen/index.html',
    category: 'Arcade',
    author: 'id Software (fan port)',
    description: 'The grandfather of first-person shooters playable in your browser. Escape the Nazi castle, shoot guards, and find the exit.',
    featured: false,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-fnaf',
    name: 'Five Nights at Freddy\'s',
    icon: '🐻',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/FNAF/index.html',
    category: 'Horror',
    author: 'Scott Cawthon (fan port)',
    description: 'Survive five nights as a security guard at a haunted pizza restaurant. Monitor cameras and manage power to avoid the animatronics.',
    featured: true,
    source: 'ChiliBowl',
  },
  {
    id: 'cb-minesweeper',
    name: 'Minesweeper',
    icon: '💣',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/CBGamesdev/chilibowlflash@main/minesweep/index.html',
    category: 'Puzzle',
    author: 'ChiliBowl',
    description: 'Uncover safe squares without triggering mines. Use number clues to figure out where the bombs are hidden.',
    featured: false,
    source: 'ChiliBowl',
  },
];