// Game entries for ServerplexOS Games app
// Generated automatically — do not edit manually

var COOLDUDE_GAMES = [
  {
      id: 'cooldude-minecraft-1-12',
      name: 'Minecraft 1.12',
      icon: '⛏️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/1.12.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-minecraft-1-5',
      name: 'Minecraft 1.5',
      icon: '⛏️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/1.5.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-minecraft-1-8',
      name: 'Minecraft 1.8',
      icon: '⛏️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/1.8.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-10-minutes-till-dawn',
      name: '10 Minutes Till Dawn',
      icon: '💣',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/10minutestilldawn.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-12-mini-battles',
      name: '12 Mini Battles',
      icon: '⚔️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/12minibattles.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-1on1-soccer',
      name: '1on1 Soccer',
      icon: '⚽',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/1on1soccer.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-1on1-tennis',
      name: '1on1 Tennis',
      icon: '🎾',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/1on1tennis.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-2048-cupcakes',
      name: '2048 Cupcakes',
      icon: '🧁',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/2048cupcakes.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-3d-flight-simulator',
      name: '3D Flight Simulator',
      icon: '✈️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/3Dflightsimulator.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-8-ball-classic',
      name: '8 Ball Classic',
      icon: '🎱',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/8ballclassic.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-alpha-1-2-6',
      name: 'Alpha_1.2.6',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/Alpha_1.2.6.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-beta-1-3',
      name: 'Beta_1.3',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/Beta_1.3.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-minecraft-indev',
      name: 'Minecraft Indev',
      icon: '⛏️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/Indev.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-agar-io',
      name: 'Agar.io',
      icon: '🦠',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/agariolite.html',
      category: 'Arcade',
      author: 'Matheus Valadares',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-among-us',
      name: 'Among Us',
      icon: '🕵️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/amongus.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-angry-birds',
      name: 'Angry Birds',
      icon: '🐦',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/angrybirds.html',
      category: 'Arcade',
      author: 'Rovio',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-angry-birds-showdown',
      name: 'Angry Birds Showdown',
      icon: '🐦',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/angrybirdsshowdown.html',
      category: 'Arcade',
      author: 'Rovio',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-angry-birds-space',
      name: 'Angry Birds Space',
      icon: '🐦',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/angrybirdsspace.html',
      category: 'Arcade',
      author: 'Rovio',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-awesome-tanks',
      name: 'Awesome Tanks',
      icon: '🛡️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/awesometanks.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-awesome-tanks-2',
      name: 'Awesome Tanks 2',
      icon: '🛡️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/awesometanks2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-backrooms',
      name: 'Backrooms',
      icon: '🚪',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/backrooms.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bad-ice-cream',
      name: 'Bad Ice Cream',
      icon: '🍦',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/badicecream.html',
      category: 'Arcade',
      author: 'Nitrome',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bad-ice-cream-2',
      name: 'Bad Ice Cream 2',
      icon: '🍦',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/badicecream2.html',
      category: 'Arcade',
      author: 'Nitrome',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bad-ice-cream-3',
      name: 'Bad Ice Cream 3',
      icon: '🍦',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/badicecream3.html',
      category: 'Arcade',
      author: 'Nitrome',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bad-parenting',
      name: 'Bad Parenting',
      icon: '😡',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/badparenting.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bad-piggies',
      name: 'Bad Piggies',
      icon: '🐖',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/badpiggies.html',
      category: 'Arcade',
      author: 'Rovio',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-basketball-legends',
      name: 'Basketball Legends',
      icon: '🏀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/basketballlegends.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-basket-bros',
      name: 'Basket Bros',
      icon: '🏀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/basketbros.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-blocky-snakes',
      name: 'Blocky Snakes',
      icon: '🐍',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/blockysnakes.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bloons-td',
      name: 'Bloons TD',
      icon: '🦍',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/bloonsTD.html',
      category: 'Arcade',
      author: 'Ninja Kiwi',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bloons-td-2',
      name: 'Bloons TD 2',
      icon: '🦍',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/bloonsTD2.html',
      category: 'Arcade',
      author: 'Ninja Kiwi',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bloons-td-3',
      name: 'Bloons TD 3',
      icon: '🦍',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/bloonsTD3.html',
      category: 'Arcade',
      author: 'Ninja Kiwi',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bloons-td-4',
      name: 'Bloons TD 4',
      icon: '🦍',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/bloonsTD4.html',
      category: 'Arcade',
      author: 'Ninja Kiwi',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bloons-td-5',
      name: 'Bloons TD 5',
      icon: '🦍',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/bloonsTD5.html',
      category: 'Arcade',
      author: 'Ninja Kiwi',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bloxorz',
      name: 'Bloxorz',
      icon: '🚨',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/bloxorz.html',
      category: 'Arcade',
      author: 'Damien Clarke',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-blumgi-racers',
      name: 'Blumgi Racers',
      icon: '🏁',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/blumgiracers.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-blumgi-rocket',
      name: 'Blumgi Rocket',
      icon: '🚀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/blumgirocket.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bob-the-robber',
      name: 'Bob The Robber',
      icon: '👴',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/bobtherobber.html',
      category: 'Arcade',
      author: 'Funtomic',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bob-the-robber-2',
      name: 'Bob The Robber 2',
      icon: '👴',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/bobtherobber2.html',
      category: 'Arcade',
      author: 'Funtomic',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bob-the-robber-5',
      name: 'Bob The Robber 5',
      icon: '👴',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/bobtherobber5.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bouncy-motors',
      name: 'Bouncy Motors',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/bouncymotors.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bowmasters',
      name: 'Bowmasters',
      icon: '🏹',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/bowmasters.html',
      category: 'Arcade',
      author: 'Playgendary',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-breaking-the-bank',
      name: 'Breaking The Bank',
      icon: '🏦',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/breakingthebank.html',
      category: 'Arcade',
      author: 'PuffballsUnited',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-bubble-shooter',
      name: 'Bubble Shooter',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/bubbleshooter.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-candy-crush',
      name: 'Candy Crush',
      icon: '🍬',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/candycrush.html',
      category: 'Arcade',
      author: 'King',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-capybara-clicker',
      name: 'Capybara Clicker',
      icon: '🦓',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/capybaraclicker.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-car-drawing',
      name: 'Car Drawing',
      icon: '🚌',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/cardrawing.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-car-king-arena',
      name: 'Car King Arena',
      icon: '🏆',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/carkingarena.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-choppy-orc',
      name: 'Choppy Orc',
      icon: '🐉',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/choppyorc.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-circloo',
      name: 'circloO',
      icon: '○',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/circloO.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-circloo-2',
      name: 'circloO 2',
      icon: '○',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/circloO2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-clash-of-vikings',
      name: 'Clash of Vikings',
      icon: '⚔️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/clashofvikings.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-clean-up-io',
      name: 'Clean Up.io',
      icon: '🧹',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/cleanupio.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-cluster-rush',
      name: 'Cluster Rush',
      icon: '🚨',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/clusterrush.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-crazy-cars',
      name: 'Crazy Cars',
      icon: '🏁',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/crazycars.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-crazy-crash-landing',
      name: 'Crazy Crash Landing',
      icon: '✈️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/crazycrashlanding.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-crazy-motorcycle',
      name: 'Crazy Motorcycle',
      icon: '🏃',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/crazymotorcycle.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-cut-the-rope',
      name: 'Cut The Rope',
      icon: '🌟',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/cuttherope.html',
      category: 'Arcade',
      author: 'ZeptoLab',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-dadish',
      name: 'Dadish',
      icon: '🥕',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/dadish.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-dadish-2',
      name: 'Dadish 2',
      icon: '🥕',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/dadish2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-dadish-3',
      name: 'Dadish 3',
      icon: '🥕',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/dadish3.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-death-chase',
      name: 'Death Chase',
      icon: '💀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/deathchase.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-death-run-3d',
      name: 'Death Run 3D',
      icon: '🏃',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/deathrun3D.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-demolition-derby-crash-racing',
      name: 'Demolition Derby Crash Racing',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/demolitionderbycrashracing.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-doodle-jump',
      name: 'Doodle Jump',
      icon: '🐸',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/doodlejump.html',
      category: 'Arcade',
      author: 'Lima Sky',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-draw-climber',
      name: 'Draw Climber',
      icon: '✏️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/drawclimber.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-dreadhead-parkour',
      name: 'Dreadhead Parkour',
      icon: '🏃',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/dreadheadparkour.htm',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-drift-boss',
      name: 'Drift Boss',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/driftboss.htm',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-duck-life',
      name: 'Duck Life',
      icon: '🦆',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/ducklife.html',
      category: 'Arcade',
      author: 'Wix Games',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-ducklings-io',
      name: 'Ducklings.io',
      icon: '🦆',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/ducklingsio.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-eagle-ride',
      name: 'Eagle Ride',
      icon: '🛩️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/eagleride.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-earn-to-die',
      name: 'Earn To Die',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/earntodie.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-earn-to-die-2',
      name: 'Earn To Die 2',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/earntodie2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-eggy-car',
      name: 'Eggy Car',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/eggycar.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-elastic-face',
      name: 'Elastic Face',
      icon: '😜',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/elasticface.htm',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-escape-road',
      name: 'Escape Road',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/escaperoad.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-escape-road-2',
      name: 'Escape Road 2',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/escaperoad2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-escaping-the-prison',
      name: 'Escaping The Prison',
      icon: '🚪',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/escapingtheprison.html',
      category: 'Arcade',
      author: 'PuffballsUnited',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-evil-glitch',
      name: 'Evil Glitch',
      icon: '👻',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/evilglitch.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-fancy-pants-adventure',
      name: 'Fancy Pants Adventure',
      icon: '🎁',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/fancypantsadventure.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-fancy-pants-adventure-2',
      name: 'Fancy Pants Adventure 2',
      icon: '🎁',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/fancypantsadventure2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-fireboy-and-watergirl',
      name: 'Fireboy and Watergirl',
      icon: '🔥',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/fireboyandwatergirl.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-fireboy-and-watergirl-2',
      name: 'Fireboy and Watergirl 2',
      icon: '🔥',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/fireboyandwatergirl2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-fireboy-and-watergirl-3',
      name: 'Fireboy and Watergirl 3',
      icon: '🔥',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/fireboyandwatergirl3.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-fireboy-and-watergirl-4',
      name: 'Fireboy and Watergirl 4',
      icon: '🔥',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/fireboyandwatergirl4.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-flappy-bird',
      name: 'Flappy Bird',
      icon: '🐦',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/flappybird.html',
      category: 'Arcade',
      author: 'Dong Nguyen',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-flood-runner-2',
      name: 'Flood Runner 2',
      icon: '💧',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/floodrunner2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-flood-runner-3',
      name: 'Flood Runner 3',
      icon: '💧',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/floodrunner3.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-flood-runner-4',
      name: 'Flood Runner 4',
      icon: '💧',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/floodrunner4.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-football-bros',
      name: 'Football Bros',
      icon: '🏈',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/footballbros.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-football-legends',
      name: 'Football Legends',
      icon: '🏈',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/footballlegends.html',
      category: 'Arcade',
      author: 'Madpuffers',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-free-rider-3',
      name: 'Free Rider 3',
      icon: '🏃',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/freerider3.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-fruit-ninja',
      name: 'Fruit Ninja',
      icon: '🔪',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/fruitninja.html',
      category: 'Arcade',
      author: 'Halfbrick',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-funny-battle',
      name: 'Funny Battle',
      icon: '😂',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/funnybattle.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-funny-battle-2',
      name: 'Funny Battle 2',
      icon: '😂',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/funnybattle2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-funny-mad-racing',
      name: 'Funny Mad Racing',
      icon: '😄',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/funnymadracing.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-funny-shooter-2',
      name: 'Funny Shooter 2',
      icon: '🔫',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/funnyshooter2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-geometry-dash',
      name: 'Geometry Dash',
      icon: '🎨',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/geometrydash.html',
      category: 'Arcade',
      author: 'RobTop Games',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-geometry-vibes',
      name: 'Geometry Vibes',
      icon: '🎨',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/geometryvibes.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-getaway-shootout',
      name: 'Getaway Shootout',
      icon: '🔫',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/getawayshootout.htm',
      category: 'Arcade',
      author: 'New Eich Games',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-get-on-top',
      name: 'Get On Top',
      icon: '👪',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/getontop.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-gladihoppers',
      name: 'Gladihoppers',
      icon: '⚔️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/gladihoppers.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-google-baseball',
      name: 'Google Baseball',
      icon: '⚾',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/googlebaseball.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-google-dino',
      name: 'Google Dino',
      icon: '🦖',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/googledino.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-granny-2',
      name: 'Granny 2',
      icon: '👵',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/granny2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-guess-their-answer',
      name: 'Guess Their Answer',
      icon: '🧠',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/guesstheiranswer.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-hanger-2',
      name: 'Hanger 2',
      icon: '🎢',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/hanger2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-happy-wheels',
      name: 'Happy Wheels',
      icon: '🚲',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/happywheels.html',
      category: 'Arcade',
      author: 'Fancy Force',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-helix-jump',
      name: 'Helix Jump',
      icon: '🔺',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/helixjump.html',
      category: 'Arcade',
      author: 'Voodoo',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-highway-traffic',
      name: 'Highway Traffic',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/highwaytraffic.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-hill-climb-racing-lite',
      name: 'Hill Climb Racing Lite',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/hillclimbracinglite.html',
      category: 'Arcade',
      author: 'Fingersoft',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-house-of-hazards',
      name: 'House of Hazards',
      icon: '🏠',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/houseofhazards.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-hover-racer-drive',
      name: 'Hover Racer Drive',
      icon: '🚀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/hoverracerdrive.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-iron-snout',
      name: 'Iron Snout',
      icon: '🐽',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/ironsnout.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-jetpack-joyride',
      name: 'Jetpack Joyride',
      icon: '🚀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/jetpackjoyride.html',
      category: 'Arcade',
      author: 'Halfbrick',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-johnny-trigger',
      name: 'Johnny Trigger',
      icon: '🔫',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/johnnytrigger.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-jumping-shell',
      name: 'Jumping Shell',
      icon: '🐢',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/jumpingshell.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-karate-bros',
      name: 'Karate Bros',
      icon: '🥋',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/karatebros.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-kart-bros',
      name: 'Kart Bros',
      icon: '🏁',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/kartbros.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-learn-to-fly',
      name: 'Learn To Fly',
      icon: '🐧',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/learntofly.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-learn-to-fly-idle',
      name: 'Learn To Fly Idle',
      icon: '🐧',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/learntoflyidle.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-level-devil',
      name: 'Level Devil',
      icon: '👿',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/leveldevil.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-madalin-stunt-cars-2',
      name: 'Madalin Stunt Cars 2',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/madalinstuntcars2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-melon-playground',
      name: 'Melon Playground',
      icon: '🍈',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/melonplayground.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-merge-round-racers',
      name: 'Merge Round Racers',
      icon: '🏁',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/mergeroundracers.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-minesweeper',
      name: 'Minesweeper',
      icon: '💣',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/minesweeper.html',
      category: 'Arcade',
      author: 'Microsoft',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-monster-tracks',
      name: 'Monster Tracks',
      icon: '🚛',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/monstertracks.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-moto-x3m-pool-party',
      name: 'Moto X3M Pool Party',
      icon: '🏃',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/motox3mpoolparty.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-moto-x3m-spooky-land',
      name: 'Moto X3M Spooky Land',
      icon: '🏃',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/motox3mspookyland.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-moto-x3m-winter',
      name: 'Moto X3M Winter',
      icon: '🏃',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/motox3mwinter.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-noob-miner',
      name: 'Noob Miner',
      icon: '⛏️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/noobminer.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-opposite-day',
      name: 'Opposite Day',
      icon: '🔄',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/oppositeday.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-ovo-3-dimensions',
      name: 'OVO 3 Dimensions',
      icon: '🧩',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/ovo3dimensions.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-pacman',
      name: 'Pacman',
      icon: '👻',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/pacman.html',
      category: 'Arcade',
      author: 'Namco',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-paper-io-2',
      name: 'Paper.io 2',
      icon: '📄',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/paperio2.htm',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-parking-fury',
      name: 'Parking Fury',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/parkingfury.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-parking-fury-2',
      name: 'Parking Fury 2',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/parkingfury2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-parking-fury-3',
      name: 'Parking Fury 3',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/parkingfury3.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-ping-pong-chaos',
      name: 'Ping Pong Chaos',
      icon: '🏓',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/pingpongchaos.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-pixel-speedrun',
      name: 'Pixel Speedrun',
      icon: '👾',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/pixelspeedrun.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-plants-vs-zombies',
      name: 'Plants vs Zombies',
      icon: '🌱',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/plantsvszombies.html',
      category: 'Arcade',
      author: 'PopCap',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-plonky',
      name: 'Plonky',
      icon: '🎹',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/plonky.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-poor-bunny',
      name: 'Poor Bunny',
      icon: '🐰',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/poorbunny.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-pou',
      name: 'Pou',
      icon: '🐣',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/pou.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-ragdoll-hit',
      name: 'Ragdoll Hit',
      icon: '🐢',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/ragdollhit.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-red-ball-4-vol-1',
      name: 'Red Ball 4 Vol 1',
      icon: '🔴',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/redball4vol1.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-red-ball-4-vol-2',
      name: 'Red Ball 4 Vol 2',
      icon: '🔴',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/redball4vol2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-red-ball-4-vol-3',
      name: 'Red Ball 4 Vol 3',
      icon: '🔴',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/redball4vol3.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-retro-highway',
      name: 'Retro Highway',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/retrohighway.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-retro-ping-pong',
      name: 'Retro Ping Pong',
      icon: '🏓',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/retropingpong.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-riddle-school',
      name: 'Riddle School',
      icon: '🏫',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/riddleschool.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-riddle-school-2',
      name: 'Riddle School 2',
      icon: '🏫',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/riddleschool2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-riddle-school-3',
      name: 'Riddle School 3',
      icon: '🏫',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/riddleschool3.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-riddle-school-4',
      name: 'Riddle School 4',
      icon: '🏫',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/riddleschool4.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-riddle-school-5',
      name: 'Riddle School 5',
      icon: '🏫',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/riddleschool5.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-riddle-transfer',
      name: 'Riddle Transfer',
      icon: '🔄',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/riddletransfer.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-riddle-transfer-2',
      name: 'Riddle Transfer 2',
      icon: '🔄',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/riddletransfer2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-rocket-soccer-derby',
      name: 'Rocket Soccer Derby',
      icon: '🚀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/rocketsoccerderby.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-run-3',
      name: 'Run 3',
      icon: '🏃',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/run3.html',
      category: 'Arcade',
      author: 'Player 03',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-sand-game',
      name: 'Sand Game',
      icon: '🏖️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/sandgame.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-short-life',
      name: 'Short Life',
      icon: '💀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/shortlife.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-slope-2-player',
      name: 'Slope 2 Player',
      icon: '🟩',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/slope2player.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-slow-roads',
      name: 'Slow Roads',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/slowroads.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-super-mario-63',
      name: 'Super Mario 63',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/sm63.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-super-mario-64',
      name: 'Super Mario 64',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/sm64.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-snow-rider',
      name: 'Snow Rider',
      icon: '🚿',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/snowrider.htm',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-snow-road',
      name: 'Snow Road',
      icon: '🎿',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/snowroad.htm',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-soccer-bros',
      name: 'Soccer Bros',
      icon: '⚽',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/soccerbros.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-spacebar-clicker',
      name: 'Spacebar Clicker',
      icon: '💾',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/spacebarclicker.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-space-is-key',
      name: 'Space Is Key',
      icon: '💾',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/spaceiskey.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-space-is-key-2',
      name: 'Space Is Key 2',
      icon: '💾',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/spaceiskey2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-speed-stars',
      name: 'Speed Stars',
      icon: '🏃',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/speedstars.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-sprunki',
      name: 'Sprunki',
      icon: '🎵',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/sprunki.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-stack',
      name: 'Stack',
      icon: '🔳',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/stack.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-stacktris',
      name: 'Stacktris',
      icon: '🔳',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/stacktris.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-state-io',
      name: 'State.io',
      icon: '🏰',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/stateio.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-stick-archers-battle',
      name: 'Stick Archers Battle',
      icon: '🏹',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/stickarchersbattle.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-stick-fighter',
      name: 'Stick Fighter',
      icon: '🥊',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/stickfighter.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-stickman-hook',
      name: 'Stickman Hook',
      icon: '🪜',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/stickmanhook.html',
      category: 'Arcade',
      author: 'Madbox',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-stick-merge',
      name: 'Stick Merge',
      icon: '👥',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/stickmerge.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-subway-surfers--beijing',
      name: 'Subway Surfers: Beijing',
      icon: '🚇',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/subwaysurfersbeijing.html',
      category: 'Arcade',
      author: 'SYBO Games',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-subway-surfers--havana',
      name: 'Subway Surfers: Havana',
      icon: '🚇',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/subwaysurfershavana.html',
      category: 'Arcade',
      author: 'SYBO Games',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-subway-surfers--san-francisco',
      name: 'Subway Surfers: San Francisco',
      icon: '🚇',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/subwaysurferssanfrancisco.html',
      category: 'Arcade',
      author: 'SYBO Games',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-superbike-the-champion',
      name: 'Superbike the Champion',
      icon: '🏁',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/superbikethechampion.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-superhot',
      name: 'Superhot',
      icon: '🔫',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/superhot.html',
      category: 'Arcade',
      author: 'SUPERHOT Team',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-super-liquid-soccer',
      name: 'Super Liquid Soccer',
      icon: '⚽',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/superliquidsoccer.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-super-star-car',
      name: 'Super Star Car',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/superstarcar.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-table-tennis-world-tour',
      name: 'Table Tennis World Tour',
      icon: '🏓',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/tabletennisworldtour.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-tag',
      name: 'Tag',
      icon: '🏃',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/tag.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-tap-road',
      name: 'Tap Road',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/taproad.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-temple-of-boom',
      name: 'Temple of Boom',
      icon: '🏰',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/templeofboom.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-temple-run-2',
      name: 'Temple Run 2',
      icon: '🏃',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/templerun2.htm',
      category: 'Arcade',
      author: 'Imangi Studios',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-territorial-io',
      name: 'Territorial.io',
      icon: '🏰',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/territorialio.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-the-impossible-quiz',
      name: 'The Impossible Quiz',
      icon: '❓',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/theimpossiblequiz.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-the-impossible-quiz-2',
      name: 'The Impossible Quiz 2',
      icon: '❓',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/theimpossiblequiz2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-there-is-no-game',
      name: 'There Is No Game',
      icon: '⛔',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/thereisnog.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-they-are-coming',
      name: 'They Are Coming',
      icon: '🧟',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/theyarecoming.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-this-is-the-only-level',
      name: 'This Is The Only Level',
      icon: '🔽',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/thisistheonlylevel.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-this-is-the-only-level-too',
      name: 'This Is The Only Level Too',
      icon: '🔽',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/thisistheonlyleveltoo.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-time-shooter-2',
      name: 'Time Shooter 2',
      icon: '⏰',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/timeshooter2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-time-shooter-3',
      name: 'Time Shooter 3',
      icon: '⏰',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/timeshooter3.htm',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-trap-the-cat',
      name: 'Trap The Cat',
      icon: '🐱',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/trapthecat.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-trivia-crack',
      name: 'Trivia Crack',
      icon: '🧠',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/triviacrack.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-tube-jumpers',
      name: 'Tube Jumpers',
      icon: '🚧',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/tubejumpers.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-tunnel-rush',
      name: 'Tunnel Rush',
      icon: '🌀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/tunnelrush.html',
      category: 'Arcade',
      author: 'Deer Cat',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-unicycle-hero',
      name: 'Unicycle Hero',
      icon: '🚲',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/unicyclehero.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-war--the-knights',
      name: 'War: The Knights',
      icon: '⚔️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/wartheknights.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-we-become-what-we-behold',
      name: 'We Become What We Behold',
      icon: '🖼️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/webecomewhatwebehold.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-wheelie-bike',
      name: 'Wheelie Bike',
      icon: '🚴',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/wheeliebike.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-wheely',
      name: 'Wheely',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/wheely.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-wheely-2',
      name: 'Wheely 2',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/wheely2.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-wheely-3',
      name: 'Wheely 3',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/wheely3.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-wheely-4',
      name: 'Wheely 4',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/wheely4.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-wheely-5',
      name: 'Wheely 5',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/wheely5.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-wheely-6',
      name: 'Wheely 6',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/wheely6.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-wheely-7',
      name: 'Wheely 7',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/wheely7.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-wheely-8',
      name: 'Wheely 8',
      icon: '🚗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/wheely8.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-wordle-unlimited',
      name: 'Wordle Unlimited',
      icon: '🟩',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/wordleunlimited.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-wrestle-bros',
      name: 'Wrestle Bros',
      icon: '🥊',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/wrestlebros.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },

  {
      id: 'cooldude-zombie-rush',
      name: 'Zombie Rush',
      icon: '🧟',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/CoolDude2349/Offline-HTML-Games-Pack@master/offline/zombierush.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'CoolDude',
    },
];