// ══════════════════════════════════════════════════════════════
//  GAMES.JS — os-apps/games/games.js
//
//  Game registry for ServerplexOS Games app.
//  Each entry must have a unique id: (source)-(game-name)
//
//  Sources:
//    Community  Serverplex/ServerplexOS-Games GitHub repo
//    GN-Math    gn-math/html GitHub (jsdelivr.net/gh/gn-math/html@main/N.html)
//
//  Categories (use exactly one):
//    Action | Puzzle | Adventure | Arcade | Sports | Strategy | Multiplayer | Other
//
//  cover: leave empty string, fill in later
//  featured: always false
// ══════════════════════════════════════════════════════════════

var MANUAL_GAMES = [
{
  id: 'community-1v1-lol',
  name: '1v1.LOL',
  icon: '🎯',
  cover: 'https://worldsapps.com/img/apps/1508620125/icon-download-1v1-lol-battle-royale-game.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/1-9/1v1.html',
  category: 'Action',
  author: 'JustPlay.LOL',
  description: 'A fast-paced third-person shooter with Fortnite-style building, featuring 1v1 duels, box fights, and competitive modes.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-2048',
  name: '2048',
  icon: '🔢',
  cover: 'https://logodix.com/logo/1649541.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/1-9/2048.html',
  category: 'Puzzle',
  author: 'Gabriele Cirulli',
  description: 'A highly addictive sliding‑tile puzzle where you combine matching numbers to create larger values, planning each move carefully to avoid filling the board while pushing toward the 2048 tile.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-adventure-capitalist',
  name: 'Adventure Capitalist',
  icon: '💰',
  cover: 'https://cdn2.steamgriddb.com/icon_thumb/29c5bc899fe290c1dcdab537dea8354d.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/A/AdventureCapitalist.html',
  category: 'Strategy',
  author: 'Hyper Hippo Games',
  description: 'An idle business simulation game where you invest in increasingly profitable ventures, hire managers to automate production, and expand your empire across Earth, the Moon, and Mars while chasing exponential growth.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-among-us-fangame',
  name: 'Among Us (Fan Game)',
  icon: '🕵️‍♂️',
  cover: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/73206bd9-257c-4f50-b1f3-59a306e24084/dfq2s3e-05782889-08c7-45d8-ab45-72232e9ec880.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzczMjA2YmQ5LTI1N2MtNGY1MC1iMWYzLTU5YTMwNmUyNDA4NFwvZGZxMnMzZS0wNTc4Mjg4OS0wOGM3LTQ1ZDgtYWI0NS03MjIzMmU5ZWM4ODAucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.tsJdAPG3U5txNM2O82P9Vyvv3ljM_UT4878py0ePH60',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/A/AmongUs.html',
  category: 'Multiplayer',
  author: 'Fan‑made / Unknown',
  description: 'A browser‑based recreation of the classic social‑deduction gameplay, featuring tasks, sabotage, emergency meetings, and simple offline or local play without the official servers.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-backrooms-fan',
  name: 'Backrooms 3D (FanGame)',
  icon: '🚪',
  cover: 'https://images.sftcdn.net/images/t_app-icon-l/p/8ec9a73e-204d-4402-af6b-3df5ce85b354/1627129876/backrooms-backrooms-icn.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/B/Backrooms.html',
  category: 'Adventure',
  author: 'Fan-Made / Unknown',
  description: 'A fan-made exploration horror game set in the endless yellow halls of Level 0, focusing on eerie atmosphere, liminal spaces, and the unsettling search for an exit while avoiding mysterious entities.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-bacon-may-die',
  name: 'Bacon May Die',
  icon: '🥓',
  cover: 'https://th.bing.com/th/id/OIP.CgwwOm35K21jOca_CzZs3AHaHa?w=163&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/B/BaconMayDie.html',
  category: 'Action',
  author: 'SnoutUp Games',
  description: 'A frantic beat-em-up where you play as a heavily armed pig battling waves of goofy enemies, unlocking weapons, outfits, and co‑op chaos while surviving increasingly intense combat.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-baldis-basics-fan',
  name: "Baldi's Basics (Fan Game)",
  icon: '📓',
  cover: 'https://cdn2.steamgriddb.com/icon/d23a0a2880738ad75a04b1c9dc7d9b73/32/256x256.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/B/BaldiBasics.html',
  category: 'Adventure',
  author: 'Fan-Made / Unknown',
  description: 'A fan-made take on the Baldi’s Basics formula, featuring notebook collecting, maze-like school exploration, and custom twists on the original characters and mechanics while keeping the surreal edutainment-horror style.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-baseball-bros',
  name: 'Baseball Bros',
  icon: '⚾',
  cover: 'https://baseballbrosgame.io/cache/data/image/game/baseball-bros-io-game-m208x208.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/B/BaseballBros.html',
  category: 'Sports',
  author: 'Fan-Made / Unknown',
  description: 'A fast-paced arcade baseball game focused on timing your swings, hitting for distance, collecting power-ups, and chaining perfect hits to rack up massive scores across increasingly challenging rounds.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-basket-random',
  name: 'Basket Random',
  icon: '🏀',
  cover: 'https://play-lh.googleusercontent.com/gP8T5Z1O-ngxIloiwcBZzrzyLPYDp0R_1BDNKUDZboIRPVImeyWI8-7aExvB9gAGNKc',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/B/BasketRandom.html',
  category: 'Sports',
  author: 'RHM Interactive',
  description: 'A chaotic physics-based basketball game where each round changes the court, gravity, and player movement, creating unpredictable and hilarious matches as you try to score before your opponent.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-basketball-bros',
  name: 'Basketball Bros',
  icon: '🏀',
  cover: 'https://www.basketball-bros.io/basketball-bros/logo.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/B/BasketballBros.html',
  category: 'Sports',
  author: 'Fan-Made / Unknown',
  description: 'A fast-paced 1v1 arcade basketball game focused on quick movement, flashy dunks, simple controls, and chaotic back-and-forth scoring. Players outmaneuver opponents, time jumps, and use aggressive blocks to win short, intense matches.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-basketball-stars',
  name: 'Basketball Stars',
  icon: '🏀',
  cover: 'https://img.gamedistribution.com/69d78d071f704fa183d75b4114ae40ec-512x512.jpeg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/B/BasketballStars.html',
  category: 'Sports',
  author: 'Madpuffers',
  description: 'A fast-paced 1v1 and 2v2 basketball game featuring smooth animations, skill-based shooting, stealing, and blocking, with unlockable characters, outfits, and competitive tournament modes.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-bit-planes',
  name: 'Bit Planes',
  icon: '🛩️',
  cover: 'https://th.bing.com/th/id/OIP.3uAc7AgCcWCTs2y_x2k0lgHaHa?w=166&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/B/BitLife.html',
  category: 'Arcade',
  author: 'Fan-Made / Unknown',
  description: 'A retro‑style arcade flying game where you pilot pixel aircraft through waves of enemies, dodge projectiles, collect power-ups, and survive increasingly intense levels with simple but fast-paced controls.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-bitlife',
  name: 'BitLife',
  icon: '📘',
  cover: 'https://images.yourstory.com/cs/images/companies/a7dac95e969c-bitlife-1672665626585.png?fm=auto&ar=1:1&mode=fill&fill=solid&fill-color=fff',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/B/BitLife.html',
  category: 'Other',
  author: 'Candywriter, LLC',
  description: 'A life simulation game where every decision shapes your character’s journey from birth to death, letting you choose careers, relationships, education, and risky or wholesome paths to create unique life stories.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-bloxd-io',
  name: 'Bloxd.io',
  icon: '🧱',
  cover: 'https://img-hws.y8.com/cloud/v2-y8-studio-banner/361/bloxd-1667995919-logo.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/B/Bloxd.html',
  category: 'Multiplayer',
  author: 'Bloxd.io',
  description: 'A multiplayer block‑based game featuring parkour, sandbox building, creative modes, and competitive minigames inspired by Minecraft-style movement and mechanics.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-boxing-random',
  name: 'Boxing Random',
  icon: '🥊',
  cover: 'https://games76ez.com/uploads/2025/8/boxing-random.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/B/BoxingRandom.html',
  category: 'Sports',
  author: 'RHM Interactive',
  description: 'A chaotic physics-based boxing game where each round changes fighter positions, platforms, and conditions, creating unpredictable and hilarious one-button matches.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-chess',
  name: 'Chess',
  icon: '♟️',
  cover: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/8a9db7bb-486f-4f74-ba59-513e78b175c4/dfy1l6k-3891a94b-1b8b-4d35-b0e5-c28da471c789.png/v1/fill/w_512,h_512/chess_com___icon_by_shamo45_dfy1l6k-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvOGE5ZGI3YmItNDg2Zi00Zjc0LWJhNTktNTEzZTc4YjE3NWM0XC9kZnkxbDZrLTM4OTFhOTRiLTFiOGItNGQzNS1iMGU1LWMyOGRhNDcxYzc4OS5wbmciLCJ3aWR0aCI6Ijw9NTEyIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.KJBGUzMYClczE0wyHEWIpcTb1D-4JXceZQJJzcH_ER8',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/C/chess.html',
  category: 'Strategy',
  author: 'Unknown',
  description: 'A classic two‑player strategy game focused on tactical positioning, long-term planning, and outmaneuvering the opponent’s king through a combination of offense and defense.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-cookie-clicker',
  name: 'Cookie Clicker',
  icon: '🍪',
  cover: 'https://play-lh.googleusercontent.com/Z1MOuuiD05ZN5LkVmMEvKF0mqAc-FknaQ2j8s4dZiO-LSPQX4EEA3RVJdlQEtxe96ok',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/C/CookieClicker.html',
  category: 'Strategy',
  author: 'Orteil / DashNet',
  description: 'An incremental idle game where you generate cookies by clicking and by purchasing buildings, upgrades, and synergies that exponentially increase your cookies per second.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-core-ball',
  name: 'Core Ball',
  icon: '🎯',
  cover: 'https://mariogames.io/data/image/game/coreball.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/C/CoreBall.html',
  category: 'Arcade',
  author: 'Unknown',
  description: 'A timing-based arcade game where you launch numbered balls onto a rotating core without letting them collide, increasing in speed and difficulty across dozens of levels.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-crazy-cattle-3d',
  name: 'Crazy Cattle 3D',
  icon: '🐄',
  cover: 'https://crazycattle3dgithub.io/data/image/crazy-cattle-3d-online.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/C/CrazyCattle.html',
  category: 'Action',
  author: 'Unknown',
  description: 'A chaotic physics-based action game where you control a wild cow rampaging through farms and towns, smashing obstacles, avoiding hazards, and maintaining momentum to cause maximum destruction.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-crossy-road',
  name: 'Crossy Road',
  icon: '🐔',
  cover: 'https://cdn.jim-nielsen.com/ios/1024/crossy-road-2022-05-13.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/C/CrossyRoad.html',
  category: 'Arcade',
  author: 'Hipster Whale',
  description: 'An endless arcade hopper where you dodge cars, trains, and hazards while crossing roads, rivers, and tracks, aiming to travel as far as possible and unlock dozens of quirky characters.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-deltarune',
  name: 'Deltarune',
  icon: '⭐',
  cover: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/8ef1af63-5387-4149-9fc7-91af014f7541/deurk9t-fa41a1c5-0302-48a0-9243-08f5a5ae564c.png/v1/fill/w_512,h_512/deltarune_dock_icon_by_usednoo25_by_usednoo25_deurk9t-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvOGVmMWFmNjMtNTM4Ny00MTQ5LTlmYzctOTFhZjAxNGY3NTQxXC9kZXVyazl0LWZhNDFhMWM1LTAzMDItNDhhMC05MjQzLTA4ZjVhNWFlNTY0Yy5wbmciLCJ3aWR0aCI6Ijw9NTEyIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.eF0TmiWOKHqzO5gQ2DRdwN1fX3kdw0uva-IDPwABz2U',
  url: 'skip',
  category: 'Adventure',
  author: 'Toby Fox',
  description: 'A story-driven adventure game where you and your classmates are pulled into a mysterious world, facing choices, puzzles, and turn-based encounters that shape the fate of its characters.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-drive-mad',
  name: 'Drive Mad',
  icon: '🚗',
  cover: 'https://th.bing.com/th/id/OIP.odp26kFzqu9k2p8kmeAJGgHaHa?w=178&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/D/DriveMad.html',
  category: 'Arcade',
  author: 'Unknown',
  description: 'A physics-based driving game where you navigate unstable vehicles across tricky obstacle courses, balancing speed and control to reach the finish without flipping.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-eaglercraft-1-8-8-forge',
  name: 'Eaglercraft 1.8.8 Forge',
  icon: '🧩',
  cover: 'https://styles.redditmedia.com/t5_60aj9d/styles/communityIcon_serayq82g91a1.jpg?format=pjpg&s=3262e0b1499369a43c9123d5610d8fbfa462062c',
  url: '',
  category: 'Other',
  author: 'Unknown',
  description: 'A community-made Forge-compatible variant of Eaglercraft 1.8.8 that allows select Minecraft Forge 1.8.8 mods to run directly in the browser using WebAssembly, enabling modded gameplay without a local Java installation.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-eaglercraft-1-8-8-wasm',
  name: 'Eaglercraft 1.8.8 WASM',
  icon: '🌐',
  cover: 'https://styles.redditmedia.com/t5_60aj9d/styles/communityIcon_serayq82g91a1.jpg?format=pjpg&s=3262e0b1499369a43c9123d5610d8fbfa462062c',
  url: '',
  category: 'Other',
  author: 'Unknown',
  description: 'A WebAssembly-compiled version of Eaglercraft 1.8.8 designed for faster performance, improved stability, and reduced input latency, allowing Minecraft 1.8.8 gameplay directly in the browser without Java.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-eaglercraft-resent-client',
  name: 'Eaglercraft Resent Client',
  icon: '🔥',
  cover: 'https://styles.redditmedia.com/t5_60aj9d/styles/communityIcon_serayq82g91a1.jpg?format=pjpg&s=3262e0b1499369a43c9123d5610d8fbfa462062c',
  url: '',
  category: 'Other',
  author: 'Unknown',
  description: 'A custom Eaglercraft client featuring enhanced UI, cosmetics, performance tweaks, and quality-of-life improvements designed to modernize the browser-based Minecraft 1.8.8 experience.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-eaglercraft-1-12-2-wasm',
  name: 'Eaglercraft 1.12.2 WASM',
  icon: '🕸️',
  cover: 'https://styles.redditmedia.com/t5_60aj9d/styles/communityIcon_serayq82g91a1.jpg?format=pjpg&s=3262e0b1499369a43c9123d5610d8fbfa462062c',
  url: '',
  category: 'Other',
  author: 'Unknown',
  description: 'A WebAssembly-based port of Eaglercraft running Minecraft 1.12.2 in the browser, offering improved performance, mod compatibility potential, and smoother gameplay compared to JavaScript builds.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-eaglercraft-1-12-2',
  name: 'Eaglercraft 1.12.2',
  icon: '⛏️',
  cover: 'https://styles.redditmedia.com/t5_60aj9d/styles/communityIcon_serayq82g91a1.jpg?format=pjpg&s=3262e0b1499369a43c9123d5610d8fbfa462062c',
  url: '',
  category: 'Other',
  author: 'Unknown',
  description: 'A browser-based port of Minecraft 1.12.2 built using JavaScript, enabling survival and creative gameplay directly in the browser without requiring Java installation.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-eaglercraft-1-8-8-wasm',
  name: 'Eaglercraft 1.8.8 WASM',
  icon: '🌐',
  cover: 'https://styles.redditmedia.com/t5_60aj9d/styles/communityIcon_serayq82g91a1.jpg?format=pjpg&s=3262e0b1499369a43c9123d5610d8fbfa462062c',
  url: '',
  category: 'Other',
  author: 'Unknown',
  description: 'A WebAssembly-based port of Eaglercraft 1.8.8 focused on higher performance, lower input latency, and improved stability compared to JavaScript builds, enabling smooth Minecraft 1.8.8 gameplay directly in the browser.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-eaglercraft-1-8-8',
  name: 'Eaglercraft 1.8.8',
  icon: '🧱',
  cover: 'https://styles.redditmedia.com/t5_60aj9d/styles/communityIcon_serayq82g91a1.jpg?format=pjpg&s=3262e0b1499369a43c9123d5610d8fbfa462062c',
  url: '',
  category: 'Other',
  author: 'Unknown',
  description: 'A browser-based recreation of Minecraft 1.8.8 that runs using JavaScript, allowing players to enjoy survival, creative, and multiplayer gameplay directly in the browser without Java.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-eaglercraft-1-5-2',
  name: 'Eaglercraft 1.5.2',
  icon: '📦',
  cover: 'https://styles.redditmedia.com/t5_60aj9d/styles/communityIcon_serayq82g91a1.jpg?format=pjpg&s=3262e0b1499369a43c9123d5610d8fbfa462062c',
  url: '',
  category: 'Other',
  author: 'Unknown',
  description: 'A browser-based recreation of Minecraft 1.5.2 using JavaScript, offering classic survival and creative gameplay directly in the browser without requiring Java.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-epsteins-basics',
  name: "Epstein's Basics",
  icon: '📓',
  cover: 'https://th.bing.com/th/id/OIP.CeK_3tEPDN3CsJPpFaenDgHaHa?w=195&h=195&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/E/EpsteinBasics.html',
  category: 'Other',
  author: 'Unknown',
  description: "A fanmade parody remake of Baldi's Basics that replaces characters and themes with dark satirical elements, keeping the notebook-collecting gameplay and chaotic chase mechanics while reimagining the setting and cast.",
    featured: false,
  source: 'Community',
},

{
  id: 'community-five-nights-at-epsteins',
  name: "Five Nights At Epstein's",
  icon: '🕹️',
  cover: 'https://th.bing.com/th/id/OIP.GI4LJKOuMY2NA0XKl1s15wHaHa?w=157&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/F/FiveNightsAtEpstein.html',
  category: 'Other',
  author: 'Evan Productions',
  description: 'A dark satirical fan-made survival game inspired by Five Nights at Freddy’s, where players monitor cameras, manage systems, and survive five nights against exaggerated, fictionalized antagonists.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-friday-night-funkin',
  name: "Friday Night Funkin'",
  icon: '🎤',
  cover: 'https://gaamess.com/wp-content/uploads/2022/01/Friday.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/F/FridayNightFunkin.html',
  category: 'Arcade',
  author: 'Unknown',
  description: "A fanmade parody twist on Friday Night Funkin', featuring humorous remixes, altered characters, and intentionally offbeat charts while keeping the core rhythm‑battle gameplay intact.",
    featured: false,
  source: 'Community',
},

{
  id: 'community-geometry-dash-lite',
  name: 'Geometry Dash Lite',
  icon: '📦',
  cover: 'https://play-lh.googleusercontent.com/p7kWbWBFxQIrzolEqiV5uSvctLeyssZvBV7UBOX29wzZI52IdcSs4qCB_zsQJL1mt9A=s64',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/GeoDash/Lite.html',
  category: 'Arcade',
  author: 'RobTop Games',
  description: 'A fast-paced rhythm-based platformer featuring a selection of classic Geometry Dash levels, challenging players to jump, fly, and flip through obstacle-filled stages synced to energetic music.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-geometry-dash-subzero',
  name: 'Geometry Dash SubZero',
  icon: '❄️',
  cover: 'https://vignette.wikia.nocookie.net/geometry-dash/images/0/01/GeometryDashSubZero.png/revision/latest?cb=20181121033752',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/GeoDash/Subzero.html',
  category: 'Arcade',
  author: 'RobTop Games',
  description: 'A fast-paced rhythm platformer featuring three exclusive icy-themed levels with intense visuals, tight timing, and music-driven gameplay designed to push players’ reflexes to the limit.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-geometry-dash-world',
  name: 'Geometry Dash World',
  icon: '🌍',
  cover: 'https://grand-screen.com/wp-content/uploads/com.robtopx.geometrydashworld_icon.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/GeoDash/World.html',
  category: 'Arcade',
  author: 'RobTop Games',
  description: 'A bite-sized Geometry Dash experience featuring short worlds, daily levels, quests, and new monsters, offering fast-paced rhythm platforming with a focus on quick progression.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-gorilla-tag',
  name: 'Gorilla Tag',
  icon: '🦍',
  cover: 'https://th.bing.com/th/id/OIP.gVDHx01YS8hFyLYW73wCYgAAAA?w=144&h=182&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/G/GorillaTag.html',
  category: 'Other',
  author: 'Another Axiom',
  description: 'A fast-paced VR movement game where players run, jump, and climb using only their arms, featuring tag-based game modes and physics-driven locomotion in social multiplayer environments.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-granny-1',
  name: 'Granny',
  icon: '👵',
  cover: 'https://spielenmania.com/wp-content/uploads/thumbs/custom/G/granny-pc-spiel-thumbnail-spielenmania.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Granny/1.html',
  category: 'Other',
  author: 'DVloper',
  description: 'A first-person horror escape game where you must survive five days inside Granny’s house by solving puzzles, avoiding traps, and staying quiet to keep from alerting Granny, who hears every sound.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-granny-2',
  name: 'Granny Chapter Two',
  icon: '🏚️',
  cover: 'https://r2.fizzerz.com/game-source/granny-2/icon.webp',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Granny/2.html',
  category: 'Other',
  author: 'DVloper',
  description: 'A horror escape game where you must survive five days in a house patrolled by both Granny, who hears everything, and Grandpa, who has sharp vision. Solve puzzles, find items, and escape without being caught.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-granny-3',
  name: 'Granny 3',
  icon: '🔪',
  cover: 'https://grand-screen.com/wp-content/uploads/com.DVloper.Granny3_icon.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Granny/3.html',
  category: 'Other',
  author: 'DVloper',
  description: 'The third entry in the Granny horror series, featuring Granny, Grandpa, and Slendrina as you attempt to escape a larger house filled with traps, puzzles, and multiple escape routes.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-hole-io',
  name: 'Hole.io',
  icon: '🕳️',
  cover: 'https://th.bing.com/th/id/OIP.AF8S_5xvpl_ZqqxXDOIJYgAAAA?w=143&h=146&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/H/Hole.io.html',
  category: 'Arcade',
  author: 'VOODOO',
  description: 'A competitive arcade game where you control a growing black hole, swallowing objects, buildings, and opponents to become the largest hole on the map before time runs out.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-idle-breakout',
  name: 'Idle Breakout',
  icon: '🟦',
  cover: 'https://th.bing.com/th/id/OIP.NXNnMYihpqJ3DUszIleJugAAAA?w=142&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/I/IdleBreakout.html',
  category: 'Arcade',
  author: 'Kodiqi',
  description: 'An incremental twist on the classic brick‑breaker game where you buy and upgrade balls to automatically destroy bricks, earn cash, and progress through increasingly difficult levels.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-idle-miner-tycoon',
  name: 'Idle Miner Tycoon',
  icon: '⛏️',
  cover: 'https://th.bing.com/th/id/OIP.lMlU5xlCphbRwf5IWMv2NgHaHa?w=162&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/I/IdleMinerTycoon.html',
  category: 'Strategy',
  author: 'Kolibri Games',
  description: 'A management and incremental game where you automate mines, hire managers, upgrade shafts, and expand your mining empire to maximize profits over time.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-jelly-truck',
  name: 'Jelly Truck',
  icon: '🚚',
  cover: 'https://th.bing.com/th/id/OIP.Q_H90sWnp2iw5oaX8b1aYQHaHa?w=182&h=181&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/J/JellyTruck.html',
  category: 'Arcade',
  author: 'GameTornado',
  description: 'A physics-based driving game where you control a soft, jelly-like truck and navigate wobbly terrain, flipping, bouncing, and squeezing through obstacles to reach the finish.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-just-fall-lol',
  name: 'Just Fall .lol',
  icon: '🐧',
  cover: 'https://th.bing.com/th/id/OIP.pGun1ac8cl8pQ8jve7OHhgAAAA?w=154&h=159&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/J/JustFall.html',
  category: 'Multiplayer',
  author: 'JustPlay.LOL',
  description: 'A multiplayer platformer where penguins compete in obstacle-filled arenas, jumping, sliding, and surviving elimination rounds to be the last one standing.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-lucky-block-obby',
  name: 'Lucky Block Obby',
  icon: '🎲',
  cover: 'https://th.bing.com/th/id/OIP.T5oVySkjHN0DDLPg4row2QHaHa?w=184&h=184&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/L/LuckyBlockObby.html',
  category: 'Adventure',
  author: 'Unknown',
  description: 'An obstacle-course game themed around Lucky Blocks, where each block can help or sabotage you with random effects as you race to reach the end.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-monkey-mart',
  name: 'Monkey Mart',
  icon: '🐒',
  cover: 'https://th.bing.com/th/id/OIP.PBnuZm9t0XMjAY693_8BewAAAA?w=100&h=100&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/M/MonkeyMart.html',
  category: 'Arcade',
  author: 'TinyDobbins',
  description: 'A lighthearted management game where you run a supermarket as a monkey, harvesting crops, stocking shelves, serving customers, and expanding your store with new departments and upgrades.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-moto-x3m',
  name: 'Moto X3M',
  icon: '🏍️',
  cover: 'https://vodogame.com/games/moto-x3m-3/thumb_1.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/MotoX3M/1.html',
  category: 'Arcade',
  author: 'Madpuffers',
  description: 'A fast-paced motorcycle stunt game featuring physics-based movement, explosive obstacles, and time‑trial challenges across increasingly difficult levels.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-moto-x3m-2',
  name: 'Moto X3M 2',
  icon: '🏍️',
  cover: 'https://vodogame.com/games/moto-x3m-3/thumb_1.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/MotoX3M/2.html',
  category: 'Arcade',
  author: 'Madpuffers',
  description: 'The second entry in the Moto X3M series, featuring new stunt tracks, tougher obstacles, and faster-paced time‑trial challenges built on the same physics‑based motorcycle gameplay.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-moto-x3m-3',
  name: 'Moto X3M 3',
  icon: '🏍️',
  cover: 'https://vodogame.com/games/moto-x3m-3/thumb_1.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/MotoX3M/3.html',
  category: 'Arcade',
  author: 'Madpuffers',
  description: 'The third Moto X3M game, featuring faster-paced stunt tracks, new hazards, and more complex physics-based challenges as you race for the best time.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-moto-x3m-pool-party',
  name: 'Moto X3M: Pool Party',
  icon: '🏖️',
  cover: 'https://vodogame.com/games/moto-x3m-3/thumb_1.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/MotoX3M/Party.html',
  category: 'Arcade',
  author: 'Madpuffers',
  description: 'A summer-themed Moto X3M entry featuring bright beach environments, water slides, inflatables, and tricky stunt tracks that test your timing and precision.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-moto-x3m-spooky-land',
  name: 'Moto X3M: Spooky Land',
  icon: '🎃',
  cover: 'https://vodogame.com/games/moto-x3m-3/thumb_1.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/MotoX3M/Spooky.html',
  category: 'Arcade',
  author: 'Madpuffers',
  description: 'A Halloween-themed Moto X3M entry featuring haunted tracks, spooky decorations, traps, and challenging stunt sections set in a dark, eerie atmosphere.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-moto-x3m-winter',
  name: 'Moto X3M: Winter',
  icon: '❄️',
  cover: 'https://vodogame.com/games/moto-x3m-3/thumb_1.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/MotoX3M/Winter.html',
  category: 'Arcade',
  author: 'Madpuffers',
  description: 'A winter-themed Moto X3M entry featuring snowy stunt tracks, icy obstacles, slippery physics, and festive level designs that challenge your timing and control.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-n-gon',
  name: 'N-Gon',
  icon: '🔷',
  cover: 'https://th.bing.com/th/id/OIP.OPNNVlnVYy9P27pro526mAAAAA?w=173&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/N/NGon.html',
  category: 'Arcade',
  author: 'Landfall',
  description: 'A minimalist arena survival shooter where you control a tiny geometric ship and dodge, weave, and blast through escalating waves of shapes. Each enemy type has distinct movement patterns, forcing precise movement and quick reactions as the screen fills with chaos.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-operius',
  name: 'Operius',
  icon: '🚀',
  cover: 'https://th.bing.com/th/id/OIP.CLXwTUqHscDB50sIXmJohQAAAA?w=180&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'skip',
  category: 'Arcade',
  author: 'Opera GX',
  description: 'A fast, neon‑styled arcade shooter built directly into Opera GX. You pilot a small ship through tight corridors, blasting obstacles and weaving through hazards as the speed ramps up. Simple controls, clean visuals, and a pure reflex‑driven gameplay loop make it a compact but addictive high‑score chaser.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-origon-trail',
  name: 'Origon Trail',
  icon: '🛤️',
  cover: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/47264ce6-f9be-440a-8fe5-de7b40f003e7/dfo1ymj-0f534155-ae7f-40b7-9474-254ee509f0b3.png/v1/fill/w_719,h_719,strp/oregon_trail__2022____icon_by_glassjester128_dfo1ymj-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzE5IiwicGF0aCI6IlwvZlwvNDcyNjRjZTYtZjliZS00NDBhLThmZTUtZGU3YjQwZjAwM2U3XC9kZm8xeW1qLTBmNTM0MTU1LWFlN2YtNDBiNy05NDc0LTI1NGVlNTA5ZjBiMy5wbmciLCJ3aWR0aCI6Ijw9NzE5In1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.sUN9pRRsBWgE6pJc9CbO5F-GGQltlyzlg-pRsEI7SC4',
  url: 'skip',
  category: 'Adventure',
  author: 'Unknown',
  description: 'A retro‑styled parody of classic frontier survival games, sending players on a humorous but challenging journey across a pixelated wilderness. Manage supplies, avoid hazards, and make choices that determine whether your party reaches the end of the trail.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-ovo',
  name: 'OvO',
  icon: '⚪',
  cover: 'https://play-lh.googleusercontent.com/v7KwGdPjJGjJjRXn46sck4DwDBdKSeRzGN44CjiXUtKV0jjOi51Bt4wcXud0m-SkXg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/OVO/1.html',
  category: 'Arcade',
  author: 'Dedra Games',
  description: 'A fast, momentum‑based precision platformer built around sliding, wall‑jumping, and chaining movement to clear compact obstacle courses. Levels are short but technical, rewarding mastery of timing, speed, and clean execution.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-ovo-2',
  name: 'OvO 2',
  icon: '⚫',
  cover: 'https://minigamesville.com/wp-content/uploads/2025/08/OvO_Dimensions.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/OVO/2.html',
  category: 'Arcade',
  author: 'Dedra Games',
  description: 'A faster, harder evolution of the original OvO, expanding the momentum‑based platforming with trickier wall‑jumps, tighter timing windows, and more complex movement chains. Levels demand precision and mastery as you slide, launch, and parkour through increasingly technical obstacle layouts.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-ovo-3',
  name: 'OvO 3',
  icon: '⚪',
  cover: 'https://minigamesville.com/wp-content/uploads/2025/08/OvO_Dimensions.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/OVO/3.html',
  category: 'Arcade',
  author: 'Dedra Games',
  description: 'A major expansion of the OvO movement formula, introducing larger levels, new mechanics, and more technical momentum routes. Precision slides, boosted launches, and advanced wall‑tech become essential as stages grow more complex and speed‑focused.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-paper-io',
  name: 'Paper.io',
  icon: '📐',
  cover: 'https://th.bing.com/th/id/OIP.lFzDDF94ju5OMSoo8Ebx4gAAAA?w=133&h=150&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Paper.io/regular.html',
  category: 'Arcade',
  author: 'VOODOO',
  description: 'A territory‑capture arcade game where you expand your colored zone by drawing lines and enclosing shapes. Leave your trail exposed for too long and opponents can cut you off, making every expansion a risk‑reward decision in a constantly shifting arena.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-paper-io-3d',
  name: 'Paper.io 3D',
  icon: '🧊',
  cover: 'https://th.bing.com/th/id/OIP.pfpI7W6cr9veKPwKZmbVTQHaHa?w=180&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Paper.io/3D.html',
  category: 'Arcade',
  author: 'VOODOO',
  description: 'A 3D evolution of the classic territory‑capture formula, shifting the action onto rotating shapes and curved surfaces. You expand your zone by looping paths around the object while avoiding opponents who can cut your trail at any moment.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-paper-io-mania',
  name: 'Paper.io Mania',
  icon: '🌀',
  cover: 'https://th.bing.com/th/id/OIP.-rFtkXPKyoz0gK9Eby0VSwHaHa?w=184&h=184&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Paper.io/Mania.html',
  category: 'Arcade',
  author: 'VOODOO',
  description: 'A faster, more chaotic twist on the classic Paper.io formula, featuring tighter arenas, quicker movement, and aggressive opponents. You expand territory by drawing loops while defending your trail, turning every second into a high‑pressure risk‑reward decision.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-polytrack',
  name: 'PolyTrack',
  icon: '🏎️',
  cover: 'https://th.bing.com/th/id/OIP.GUY6pC4EBCFwbVmkT5jeaAHaHa?w=164&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/P/PolyTrack.html',
  category: 'Arcade',
  author: 'Unknown',
  description: 'A colorful low‑poly physics racer where you guide a tiny car across floating obstacle courses filled with jumps, loops, tight turns, and moving platforms. Precision control and quick resets make it a fast, replay‑heavy challenge built around mastering each track.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-prismarine-client',
  name: 'Prismarine Client',
  icon: '💎',
  cover: 'https://th.bing.com/th/id/OIP.1BNfULtDpw3jMkTHpd2bTAAAAA?w=177&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: '',
  category: 'Other',
  author: 'Prismarine',
  description: 'A lightweight browser-based Minecraft client recreation built for experimenting with rendering, movement, and block interaction. It captures the feel of classic Minecraft while running entirely in the browser, making it a fun tech demo and sandbox to explore.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-quantum-clicker',
  name: 'Quantum Clicker',
  icon: '⚛️',
  cover: 'https://th.bing.com/th/id/OIP.CeK_3tEPDN3CsJPpFaenDgHaHa?w=195&h=195&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/Q/QuantumClicker.html',
  category: 'Arcade',
  author: 'Unknown',
  description: 'A fast‑scaling incremental clicker built around quantum‑themed upgrades, exponential growth, and layered automation systems. You generate energy, unlock research paths, and push deeper into increasingly powerful progression loops.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-ragdoll-archers',
  name: 'Ragdoll Archers',
  icon: '🏹',
  cover: 'https://geodashlite.io/data/image/game/ragdoll-archers.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/R/RagdollArchers.html',
  category: 'Action',
  author: 'RHM Interactive',
  description: 'A physics‑driven archery dueling game where floppy ragdoll characters fire arrows, tumble, and react dynamically to hits. Precision aim, timing, and power control are key as you battle waves of enemies or face off in chaotic one‑on‑one fights.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-ragdoll-soccer',
  name: 'Ragdoll Soccer',
  icon: '⚽',
  cover: 'https://th.bing.com/th/id/OIP.98920O7j5jACX-A9TmegHQHaHa?w=161&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/R/RagdollSoccer.html',
  category: 'Sports',
  author: 'Unknown',
  description: 'A chaotic physics-based soccer game where floppy ragdoll players kick, tumble, collide, and bounce across the field. Matches are unpredictable and hilarious as momentum, timing, and wild physics determine every goal.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-redball-1',
  name: 'Red Ball 1',
  icon: '🔴',
  cover: 'https://is2-ssl.mzstatic.com/image/thumb/Purple122/v4/9e/0d/7f/9e0d7fc2-613d-26cb-aff0-558f93769dc4/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/512x512bb.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Redball/1.html',
  category: 'Arcade',
  author: 'Eugene Fedoseev',
  description: 'A classic physics-based platformer where you roll, jump, and navigate a small red ball through obstacle-filled levels. Timing, momentum, and simple puzzle elements shape each stage as you guide the ball to the goal flag.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-redball-2',
  name: 'Red Ball 2',
  icon: '🟠',
  cover: 'https://big8games.com/wp-content/uploads/2021/06/Red-ball-2.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Redball/2.html',
  category: 'Arcade',
  author: 'Eugene Fedoseev',
  description: 'The sequel expands the classic Red Ball platforming with larger levels, new obstacles, and a light storyline about recovering the king’s crown. Roll, jump, and solve simple physics puzzles while avoiding enemies and hazards.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-redball-3',
  name: 'Red Ball 3',
  icon: '🔴',
  cover: 'https://yepicdn.com/system/static/thumbs/tile_thumb/738/thumb150_red-ball-3.jpg?1492005833',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Redball/3.html',
  category: 'Arcade',
  author: 'Eugene Fedoseev',
  description: 'A story‑driven continuation of the Red Ball series where you chase down the villains who kidnapped your girlfriend. Levels introduce moving platforms, enemies, traps, and more complex physics challenges as you roll, jump, and solve light puzzles.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-redball-4-vol-1',
  name: 'Red Ball 4 (Vol. 1)',
  icon: '🔴',
  cover: 'https://buzzmavo.com/wp-content/uploads/thumbs/custom/0-9/512-5.jpeg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Redball/4.1.html',
  category: 'Arcade',
  author: 'FDG Entertainment',
  description: 'The first volume of Red Ball 4 introduces a new threat: evil squares trying to turn the world into a cube. Roll, jump, and defeat enemies across polished forest levels featuring improved physics, animations, and environmental hazards.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-redball-4-vol-2',
  name: 'Red Ball 4 (Vol. 2)',
  icon: '🔴',
  cover: 'https://buzzmavo.com/wp-content/uploads/thumbs/custom/0-9/512-5.jpeg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Redball/4.2.html',
  category: 'Arcade',
  author: 'FDG Entertainment',
  description: 'The second volume continues the fight against the evil squares, introducing factory-themed levels with conveyor belts, crushers, lasers, and more precise physics challenges. Movement timing becomes more demanding as hazards increase.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-redball-4-vol-3',
  name: 'Red Ball 4 (Vol. 3)',
  icon: '🔴',
  cover: 'https://buzzmavo.com/wp-content/uploads/thumbs/custom/0-9/512-5.jpeg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Redball/4.3.html',
  category: 'Arcade',
  author: 'FDG Entertainment',
  description: 'The third volume takes the adventure into deep industrial zones filled with lasers, crushers, moving machinery, and tougher square enemies. Precision movement and timing become essential as hazards grow more complex.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-retro-bowl',
  name: 'Retro Bowl',
  icon: '🏈',
  cover: 'https://cdn-1.webcatalog.io/catalog/poki-retro-bowl/poki-retro-bowl-icon-filled-256.png?v=1674454238752',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/R/RBowl.html',
  category: 'Arcade',
  author: 'New Star Games',
  description: 'A fan‑favorite 8‑bit style American football game focused on team management, drafting, coaching decisions, and quick arcade gameplay. Balance strategy and skill as you build a roster and lead your team to the Retro Bowl championship.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-retro-bowl-college',
  name: 'Retro Bowl College',
  icon: '🏈',
  cover: 'https://th.bing.com/th/id/OIP.wXfME16LLjR4ISgqQ1M2ZAAAAA?w=115&h=128&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/R/RBowlCollege.html',
  category: 'Arcade',
  author: 'New Star Games',
  description: 'A college‑themed spin on Retro Bowl featuring campus recruiting, player development, and fast arcade football gameplay. Build your program, manage your roster, and compete for the national championship.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-rocket-goal',
  name: 'Rocket Goal',
  icon: '🚗',
  cover: 'https://play-lh.googleusercontent.com/xYmXleDWgPjObguVDhC-hpcC8a5yP7399awTpyPdsxIzgV52VQEAndSZ9M4WhOXQQcBs248yuB_IMUKrWz061w',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/R/RocketGoal.html',
  category: 'Arcade',
  author: 'Unknown',
  description: 'A fast-paced physics soccer game where rocket-powered cars boost, flip, and slam into the ball to score goals. Simple controls and chaotic movement make every match unpredictable and fun.',
  featured: true,
},

{
  id: 'community-rocket-league-scratch-fanmade',
  name: 'Rocket League (Scratch Fanmade)',
  icon: '🚗',
  cover: 'https://img.icons8.com/fluent/1200/rocket-league.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/R/RocketLeague.html',
  category: 'Arcade',
  author: 'Fan-Made / Unknown',
  description: 'A Scratch-built recreation of Rocket League featuring simplified physics, boost mechanics, and car-based soccer gameplay. Designed as a browser-friendly fan project that captures the core idea in a lightweight form.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-rolling-sky',
  name: 'Rolling Sky',
  icon: '🟢',
  cover: 'https://images-na.ssl-images-amazon.com/images/I/61uZyMAv%2BHL.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/R/RollingSky.html',
  category: 'Arcade',
  author: 'Cheetah Mobile',
  description: 'A fast-paced reaction and rhythm game where you guide a rolling ball through obstacle-filled tracks. Each level features unique music, patterns, and hazards that demand quick reflexes and precise movement.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-rooftop-snipers',
  name: 'Rooftop Snipers',
  icon: '🔫',
  cover: 'https://images.sftcdn.net/images/t_app-icon-m/p/131a66c0-92d4-40b2-b76c-3f8c693b295c/2345816855/rooftop-snipers-unblocked-game-logo',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/R/RooftopSnipers.html',
  category: 'Arcade',
  author: 'New Eich Games',
  description: 'A chaotic two-button dueling game where recoil-heavy weapons launch players backward as they try to knock each other off a rooftop. Fast rounds, simple controls, and unpredictable physics make every match hilarious.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-rooftop-snipers-2',
  name: 'Rooftop Snipers 2',
  icon: '🔫',
  cover: 'https://images.sftcdn.net/images/t_app-icon-m/p/131a66c0-92d4-40b2-b76c-3f8c693b295c/2345816855/rooftop-snipers-unblocked-game-logo',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/R/RooftopSnipers2.html',
  category: 'Arcade',
  author: 'New Eich Games',
  description: 'A sequel that expands the original’s chaotic two-button duels with new maps, weapons, character skins, and smoother physics. Players jump, shoot, and use recoil to knock opponents off platforms in fast-paced, unpredictable matches.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-run-1',
  name: 'Run',
  icon: '👾',
  cover: 'https://www.noflashgame.com/wp-content/uploads/2021/12/run-1.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Run/1.html',
  category: 'Arcade',
  author: 'Player 03',
  description: 'A classic endless runner set inside a twisting 3D tunnel where you run, jump, and rotate the world to avoid falling into space. Levels get progressively harder as gaps widen and speed increases.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-run-2',
  name: 'Run 2',
  icon: '👾',
  cover: 'https://kevin.games/assets/images/games/run-2.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Run/2.html',
  category: 'Arcade',
  author: 'Player 03',
  description: 'A sequel that adds new characters, alternate paths, and more complex 3D tunnel platforming. Each character has unique physics, letting you choose between speed or control as you navigate twisting levels and avoid falling into space.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-slither-io',
  name: 'Slither.io',
  icon: '🐍',
  cover: 'https://th.bing.com/th/id/OIP.JR85ApfpXV4JGxQnycmHNgHaHa?w=179&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/S/Slither.html',
  category: 'Arcade',
  author: 'Steve Howse',
  description: 'A massively popular .io game where you control a glowing snake, eat pellets to grow, and outmaneuver other players to make them crash. Simple controls, smooth movement, and competitive multiplayer make it highly addictive.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-slope-1',
  name: 'Slope',
  icon: '🟩',
  cover: 'https://th.bing.com/th/id/OIP.r0PQCNQKzM9u6mN-j73sZQHaF5?w=191&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Slope/1.html',
  category: 'Arcade',
  author: 'Y8 / RobKay',
  description: 'A fast, reflex‑based downhill runner where you guide a ball through a neon 3D course. The speed increases constantly as obstacles, gaps, and sharp turns demand precise movement and quick reactions.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-slope-2',
  name: 'Slope 2',
  icon: '🟩',
  cover: 'https://th.bing.com/th/id/OIP.yJ31evfzJSioHzllLrb-JQAAAA?w=154&h=169&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Slope/2.html',
  category: 'Arcade',
  author: 'Y8 / RobKay',
  description: 'A sequel that builds on the original’s fast downhill gameplay with sharper turns, harder obstacles, and more unpredictable course layouts. Speed ramps up quickly, demanding precise control and quick reactions.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-slope-3',
  name: 'Slope 3',
  icon: '🟩',
  cover: 'https://th.bing.com/th/id/OIP.FHTE4dNZg6uWAvp9tLMVYgAAAA?w=169&h=169&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Slope/3.html',
  category: 'Arcade',
  author: 'Y8 / RobKay',
  description: 'The third entry in the Slope series, featuring faster speeds, tighter turns, and more unpredictable obstacle layouts. The difficulty ramps up quickly, demanding sharp reflexes and precise control to survive the neon downhill chaos.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-snow-rider-3d',
  name: 'Snow Rider 3D',
  icon: '🛷',
  cover: 'https://snow-rider3dgame.github.io/data/image/game/snow-rider-game.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/S/SnowRider.html',
  category: 'Arcade',
  author: 'Faramel Games',
  description: 'A fast-paced downhill sledding game where you steer through snowy mountains, dodge obstacles, collect gifts, and try to survive as long as possible. Smooth controls and endless slopes make it a high-score chase favorite.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-snowball-io',
  name: 'Snowball.io',
  icon: '❄️',
  cover: 'https://th.bing.com/th/id/OIP.IeYTLE9dQ-yP9CaS5uTD2QAAAA?w=142&h=150&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/S/Snowball.html',
  category: 'Arcade',
  author: 'Geisha Tokyo',
  description: 'A competitive arena game where you roll giant snowballs to knock opponents off the platform. Movement, timing, and positioning decide who survives as the arena shrinks and chaos increases.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-soccer-random',
  name: 'Soccer Random',
  icon: '⚽',
  cover: 'https://th.bing.com/th/id/OIP.2BAbi8rOVtnz2ugldhhlnAHaHu?w=156&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/S/SoccerRandom.html',
  category: 'Sports',
  author: 'RHM Interactive',
  description: 'A chaotic physics-based soccer game where each round changes the field, players, weather, and gravity. One-button controls make every match unpredictable, hilarious, and perfect for quick 2‑player fun.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-space-waves',
  name: 'Space Waves',
  icon: '🌌',
  cover: 'https://th.bing.com/th/id/OIP.oRL1Hv9QWUmLPCeL1hGAxgAAAA?w=158&h=169&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/S/SpaceWaves.html',
  category: 'Arcade',
  author: 'Unknown',
  description: 'A fast‑paced reaction and rhythm‑style game where you guide a ship through neon space tunnels, dodging obstacles and following wave‑like patterns. Precision timing and smooth movement are key to surviving each track.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-steal-a-brainrot',
  name: 'Steal A Brainrot',
  icon: '🧠',
  cover: 'https://th.bing.com/th/id/OIP._73hAk3mGhmtQgWdKVxlUgHaHa?w=175&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/S/StealABrainrot.html',
  category: 'Arcade',
  author: 'Unknown',
  description: 'A chaotic meme‑style reaction game where you dodge obstacles, grab power‑ups, and race to steal the “brainrot” before opponents do. Fast movement, unpredictable hazards, and humor-driven visuals define the experience.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-subway-surfers-berlin',
  name: 'Subway Surfers: Berlin',
  icon: '🖌️',
  cover: 'https://kankygames.com/assets/gamepic/gamemonetize-12881.jpg',
  url: '',
  category: 'Arcade',
  author: 'SYBO Games',
  description: 'A World Tour edition set in Germany’s vibrant capital, featuring neon-lit streets, graffiti art, techno-inspired visuals, and iconic Berlin landmarks. Players run through colorful tracks while collecting tokens and unlocking Berlin-exclusive characters and boards.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-terraria',
  name: 'Terraria',
  icon: '⛏️',
  cover: 'https://th.bing.com/th/id/OIP.mHZL_Jrro3BO6DCCXQasIAAAAA?w=158&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/T/Terraria.html',
  category: 'Adventure',
  author: 'Re-Logic',
  description: 'A 2D sandbox adventure game focused on exploration, building, crafting, and combat. Players dig, fight, and build their way through procedurally generated worlds filled with biomes, bosses, and countless items.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-tiny-fishing',
  name: 'Tiny Fishing',
  icon: '🎣',
  cover: 'https://th.bing.com/th/id/OIP.WT3fKtopo7gU5ocBGk9ZbQHaHa?w=150&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/T/TinyFishing.html',
  category: 'Arcade',
  author: 'Mad Buffer',
  description: 'A simple, addictive fishing game where you drop your line, catch fish to earn coins, and upgrade your depth, hook count, and earnings. Progressively deeper waters unlock rarer fish and bigger payouts.',
    featured: false,
  source: 'Community',
},


{
  id: 'community-tomb-of-the-mask',
  name: 'Tomb of the Mask',
  icon: '🏺',
  cover: 'https://th.bing.com/th/id/OIP.MNx6jGk4NWmIQWN8Zouk5QAAAA?w=157&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/T/TombOfTheMask.html',
  category: 'Arcade',
  author: 'Playgendary',
  description: 'A fast-paced vertical maze runner where you dash through trap-filled tombs using swipe movement. Each level mixes retro pixel art with deadly spikes, enemies, and procedurally generated layouts for quick, skill-based runs.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-tung-tung-tung-sahur-obby',
  name: 'Tung Tung Tung Sahur Obby',
  icon: '🌙',
  cover: 'https://th.bing.com/th/id/OIP.Hy10xtQZmwjaiAaNzUW8cwAAAA?w=136&h=150&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/T/TungTungTungSahurObby.html',
  category: 'Adventure',
  author: 'Unknown',
  description: 'A Ramadan‑themed obby inspired by the “tung tung tung sahur” meme, where players race through humorous nighttime obstacle courses while avoiding traps and reaching the sahur checkpoint before time runs out.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-ultrakill',
  name: 'ULTRAKILL (Demo)',
  icon: '💥',
  cover: 'https://cdn2.steamgriddb.com/icon/91ca305decc7727a939aa6f77529fbbc/32/256x256.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/U/Ultrakill.html',
  category: 'Action',
  author: 'Arsi “Hakita” Patala',
  description: 'A hyper‑fast, retro‑styled FPS where you play as a blood‑powered machine tearing through the layers of Hell. Movement tech, weapon swapping, and stylish combos define the combat as you fight demons, machines, and bosses in a brutal, skill‑based campaign.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-vex-1',
  name: 'Vex 1',
  icon: '🗡️',
  cover: 'https://assets.funnygames.org/2/19352/72762/1024x1024/vex.webp',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Vex/1.html',
  category: 'Platformer',
  author: 'Amazing Adam',
  description: 'The first entry in the Vex series, introducing fast-paced stickman platforming with deadly traps, wall jumps, sliding, and precision movement. Players navigate challenging levels filled with spikes, saws, and timing-based obstacles.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-vex-2',
  name: 'Vex 2',
  icon: '🗡️',
  cover: 'https://static4.ufreegames.io/covers/adventure/vex2.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Vex/2.html',
  category: 'Action',
  author: 'Amazing Adam',
  description: 'The sequel expands on the original with tougher levels, new traps, and smoother movement. Players navigate increasingly complex obstacle courses requiring precision timing and fast reactions.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-vex-3',
  name: 'Vex 3',
  icon: '🗡️',
  cover: 'https://img.gamedistribution.com/762c932b4db74c6da0c1d101b2da8be6-512x512.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Vex/3.html',
  category: 'Action',
  author: 'Amazing Adam',
  description: 'A major step up in difficulty featuring new stage types, hidden stars, and challenge modes. Movement is faster and levels introduce more advanced mechanics and deadly traps.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-vex-4',
  name: 'Vex 4',
  icon: '🗡️',
  cover: 'https://new66ez.github.io/img/vex4/vex4.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Vex/4.html',
  category: 'Action',
  author: 'Amazing Adam',
  description: 'Adds checkpoints, new hazards, and more polished level design. Players tackle increasingly dangerous acts with moving platforms, lasers, and precision-based challenges.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-vex-5',
  name: 'Vex 5',
  icon: '🗡️',
  cover: 'https://cdn.now.gg/apps-content/com.nowgg.h5.pub483.app51034/icon/vex-5.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Vex/5.html',
  category: 'Action',
  author: 'Amazing Adam',
  description: 'Introduces new mechanics like zip lines, timed doors, and advanced traps. The game emphasizes speedrunning, mastery, and replayability with tougher acts and bonus stages.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-vex-6',
  name: 'Vex 6',
  icon: '🗡️',
  cover: 'https://kevin.games/assets/images/new/vex-6.jpeg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Vex/6.html',
  category: 'Action',
  author: 'Amazing Adam',
  description: 'A polished entry with smoother animations, new enemies, and more dynamic hazards. Includes daily challenges, skins, and expanded level variety for long-term replay value.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-vex-7',
  name: 'Vex 7',
  icon: '🗡️',
  cover: 'https://www.plonga.com/storage/games/WsD4TcjRJRoxYo4276cBaObeBICIRsR9JgGnPHA5.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Vex/7.html',
  category: 'Action',
  author: 'Amazing Adam',
  description: 'Adds combat elements, stealth sections, and more cinematic traps. Levels are larger and more complex, blending classic Vex platforming with new action-focused mechanics.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-vex-8',
  name: 'Vex 8',
  icon: '🗡️',
  cover: 'https://imgs2.dab3games.com/vex-8-game-ft16.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Vex/8.html',
  category: 'Action',
  author: 'Amazing Adam',
  description: 'The newest entry featuring portals, multi-path levels, and advanced physics-based traps. Designed for high-skill players with intense difficulty spikes and speedrun-friendly layouts.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-vex-challenges',
  name: 'Vex Challenges',
  icon: '🔥',
  cover: 'https://slopegame.cc/upload/images/vex-challenges.webp',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Vex/Challenges.html',
  category: 'Action',
  author: 'Amazing Adam',
  description: 'A standalone challenge mode featuring short, intense levels focused on precision and speed. Each challenge tests specific skills with strict timing and deadly trap layouts.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-vex-x3m-1',
  name: 'Vex X3M',
  icon: '⚡',
  cover: 'https://imgs2.dab3games.com/vex-x3m-1373484.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Vex/VexX3M.html',
  category: 'Action',
  author: 'Fanmade / Unknown',
  description: 'A fan-made spin-off inspired by the Vex series, featuring fast-paced stickman platforming with custom levels, unique traps, and a more chaotic difficulty curve.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-vex-x3m-2',
  name: 'Vex X3M 2',
  icon: '⚡',
  cover: 'https://ragdollhitgame.org/cache/data/image/game/vex-x3m-2-m143x143.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/.Collections/Vex/2VexX3M.html',
  category: 'Action',
  author: 'Fanmade / Unknown',
  description: 'The sequel to the fan-made X3M entry, adding harder levels, new mechanics, and more unpredictable trap patterns while keeping the classic Vex-inspired movement.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-volley-random',
  name: 'Volley Random',
  icon: '🏐',
  cover: 'https://th.bing.com/th/id/OIP.fq7DBOtlWrq3zDNXq63u6wAAAA?w=143&h=150&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/V/VolleyRandom.html',
  category: 'Sports',
  author: 'RHM Interactive',
  description: 'A chaotic physics-based volleyball game where each round changes the court, players, gravity, and movement. One-button controls create unpredictable, hilarious matches perfect for quick solo or 2‑player play.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-wordle',
  name: 'Wordle',
  icon: '🟩',
  cover: 'https://th.bing.com/th/id/OIP.CwGYSrct0BTSkHsTMgdfxgAAAA?w=178&h=178&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/W/Wordle.html',
  category: 'Puzzle',
  author: 'Josh Wardle',
  description: 'A daily word‑guessing puzzle where players have six attempts to find a hidden five‑letter word. Color clues guide each guess, rewarding logic, vocabulary, and deduction.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-yandere-simulator',
  name: 'Yandere Simulator',
  icon: '🔪',
  cover: 'https://th.bing.com/th/id/OIP.YRXN6Y7uSy7ymAt5EfPlzQHaHG?w=164&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/Y/YandereSimulator.html',
  category: 'Action',
  author: 'YandereDev',
  description: 'A stealth and strategy game where you play as a yandere girl eliminating rivals to win Senpai’s affection. Players use disguises, social manipulation, traps, and stealth tactics to avoid suspicion while navigating a school environment.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-yohoho-io',
  name: 'Yohoho.io',
  icon: '🏴‍☠️',
  cover: 'https://th.bing.com/th/id/OIP.El96TM07LtcTqQljhZkjIQAAAA?w=162&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/Y/Yohoho.html',
  category: 'Action',
  author: 'Exodragon Games',
  description: 'A pirate-themed battle royale where players collect coins, grow stronger, and slash opponents on shrinking islands. Movement, timing, and positioning decide who becomes the last pirate standing.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-fnf-mario-madness',
  name: 'Friday Night Funkin: Mario Madness',
  icon: '🍄',
  cover: 'https://cdn2.steamgriddb.com/icon_thumb/1f1dd8f44c6c538628baf7c7cbf537b1.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/F/FridayNightFunkinMarioMadness.html',
  category: 'Arcade',
  author: 'Team Mania (FNF Mod Community)',
  description: 'A high‑intensity FNF mod where Boyfriend faces corrupted, horror‑themed versions of Mario characters across fast, chaotic songs and glitchy visuals inspired by creepypasta-style Mario lore.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-blackjack-classic',
  name: 'Blackjack',
  icon: '🃏',
  cover: 'https://static.vecteezy.com/system/resources/previews/007/214/654/non_2x/blackjack-color-icon-card-game-twenty-one-casino-isolated-illustration-vector.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/B/Blackjack.html',
  category: 'Strategy',
  author: 'Unknown',
  description: 'A classic card game where players try to reach 21 without going over, using strategy and probability to beat the dealer.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-ages-of-conflict',
  name: 'Ages Of Conflict',
  icon: '⚔️',
  cover: 'https://r2.fizzerz.com/game-source/ages-of-conflict/icon.webp',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/A/AgesOfConflict.html',
  category: 'Strategy',
  author: 'JokuPelle',
  description: 'A sandbox-style strategy game where nations rise, fall, and wage war across procedurally generated maps, letting players watch or influence chaotic world simulations.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-age-of-war',
  name: 'Age of War',
  icon: '🏹',
  cover: 'https://img.gamedistribution.com/9467420d5c84482e9087276338a3a7b1-512x512.jpeg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/A/AgeOfWar.html',
  category: 'Strategy',
  author: 'Max Games',
  description: 'A side‑scrolling strategy game where you evolve through eras, build units, and defend your base while pushing back enemy waves across multiple ages of warfare.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-age-of-war-2',
  name: 'Age of War 2',
  icon: '⚔️',
  cover: 'https://play-lh.googleusercontent.com/cgfjh-wXhG7rh0mCejpGwYmBw4PoDnBRQ2P6ARrHpGG0dTeP109HovgHyC_6Cqu4WA',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/A/AgeOfWar2.html',
  category: 'Strategy',
  author: 'Max Games',
  description: 'A sequel that expands the original Age of War with new eras, stronger units, improved base defenses, and more intense battles as you evolve through time to overpower enemy forces.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-duck-life-1',
  name: 'Duck Life 1',
  icon: '🦆',
  cover: 'https://laparda14.github.io/W/imgs/gameicons/duck1.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/DuckLife/1.html',
  category: 'Arcade',
  author: 'Wix Games',
  description: 'A lighthearted training game where you raise a duck by improving its running, flying, and swimming skills to compete in races and become the ultimate champion.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-duck-life-2',
  name: 'Duck Life 2',
  icon: '🏁',
  cover: 'https://avbgames.net/wp-content/uploads/2025/10/duck-life-2.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/DuckLife/2.html',
  category: 'Arcade',
  author: 'Wix Games',
  description: 'The sequel expands the duck‑training formula with new skills, tougher races, and world‑traveling tournaments as you train your duck to become a global racing champion.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-duck-life-3',
  name: 'Duck Life 3',
  icon: '🥚',
  cover: 'https://snookagames.github.io/assets/images/ducklife3.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/DuckLife/3.html',
  category: 'Arcade',
  author: 'Wix Games',
  description: 'The third entry introduces duck evolution, letting you choose different evolutionary paths with unique strengths as you train your duck through new challenges and race toward championship glory.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-duck-life-4',
  name: 'Duck Life 4',
  icon: '🏆',
  cover: 'https://gamecomets.com/thumbs/duck-life-4-duck-life-4.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/DuckLife/4.html',
  category: 'Arcade',
  author: 'Wix Games',
  description: 'The fourth game expands the series with new training minigames, larger race maps, and customizable ducks as you compete across multiple regions to become the ultimate racing champion.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-duck-life-5',
  name: 'Duck Life 5',
  icon: '👑',
  cover: 'https://ducklife4.io/storage/uploads/thumbs/duck-life-5-treasure-hunt.webp',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/DuckLife/5.html',
  category: 'Arcade',
  author: 'Wix Games',
  description: 'A treasure‑hunting adventure where you explore a massive volcano, solve puzzles, avoid traps, and collect loot while training your duck to overcome new challenges.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-learn-to-fly-1',
  name: 'Learn to Fly 1',
  icon: '🐧',
  cover: 'https://thumbnails.gamenora.com/Learn-To-Fly.webp',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/LearnToFly/1.html',
  category: 'Arcade',
  author: 'Light Bringer Games',
  description: 'A physics‑based launcher game where you help a determined penguin learn to fly by upgrading gliders, boosters, and techniques to reach greater distances.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-learn-to-fly-2',
  name: 'Learn to Fly 2',
  icon: '❄️',
  cover: 'https://origin.giantbomb.com/a/uploads/scale_small/31/316204/2848923-image.jpeg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/LearnToFly/2.html',
  category: 'Arcade',
  author: 'Light Bringer Games',
  description: 'The penguin returns with new launch mechanics, more upgrades, and tougher challenges as you try to break through icy obstacles and reach record distances.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-learn-to-fly-3',
  name: 'Learn to Fly 3',
  icon: '🚀',
  cover: 'https://media.moddb.com/images/games/1/66/65367/ThankYouCard.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/LearnToFly/3.html',
  category: 'Arcade',
  author: 'Light Bringer Games',
  description: 'A major evolution of the series where you build custom rockets, experiment with parts, and launch your penguin into space across multiple game modes.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-learn-to-fly-idle',
  name: 'Learn to Fly: Idle',
  icon: '🎯',
  cover: 'https://cdn2.steamgriddb.com/thumb/aee081bf7a6402604acf995e994c2c6e.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/LearnToFly/Idle.html',
  category: 'Arcade',
  author: 'Light Bringer Games',
  description: 'An idle spin‑off where you fire cannons at giant targets, upgrade your damage output, and automate your progress to reach massive numbers.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-grow-a-garden-offline',
  name: 'Grow a Garden',
  icon: '🌱',
  cover: 'https://growagardengame.com/assets/grow-a-garden-logo.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/G/GrowAGarden.html',
  category: 'Puzzle',
  author: 'Unknown',
  description: 'A simple offline gardening game where you plant seeds, water crops, and watch your garden grow at your own pace without needing an internet connection.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-growden-io',
  name: 'Growden.io',
  icon: '🌿',
  cover: 'https://dinosaur-game.io/data/image/game/growden-io/growden-io-game.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/G/Growden.html',
  category: 'Multiplayer',
  author: 'Unknown',
  description: 'A multiplayer garden‑growth game where players plant, water, and expand their gardens while interacting, competing, or cooperating with others in a shared world.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-plants-vs-zombies-1',
  name: 'Plants Vs Zombies 1',
  icon: '🧟‍♂️',
  cover: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/3bc2e591-7f06-4273-b443-2d3cf6346c3c/d4k7h2a-38ff6a79-6e9c-42a3-892b-fba1bb539db2.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzNiYzJlNTkxLTdmMDYtNDI3My1iNDQzLTJkM2NmNjM0NmMzY1wvZDRrN2gyYS0zOGZmNmE3OS02ZTljLTQyYTMtODkyYi1mYmExYmI1MzlkYjIucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.yldyLWsfHjT9etHvIGY2C7hR5WYA_Q8aeO2xgG9A7Ks',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/P/PlantsVsZombies.html',
  category: 'Strategy',
  author: 'PopCap Games',
  description: 'A tower‑defense classic where you place unique plants to stop waves of zombies from invading your home, balancing strategy, timing, and resource management.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-plants-vs-zombies-2',
  name: 'Plants Vs Zombies 2',
  icon: '🌻',
  cover: 'https://i.pinimg.com/originals/3e/8d/80/3e8d801fb41752c10b44482b16f89b42.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/P/PlantsVsZombies2.html',
  category: 'Strategy',
  author: 'PopCap Games',
  description: 'A time‑traveling tower‑defense sequel where you battle zombies across themed worlds, unlock new plants, and use powerful abilities to defend your brains.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-bakeria',
  name: "Papa's Bakeria",
  icon: '🥧',
  cover: 'https://gamingkool.com/wp-content/uploads/2025/07/4ED63A69-971B-4C1D-96BA-D1CA88E8B2CE.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Bakeria.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Bake pies, manage orders, and serve customers with precision in this bakery‑themed time‑management game.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-burgeria',
  name: "Papa's Burgeria",
  icon: '🍔',
  cover: 'https://gogamego.io/wp-content/uploads/thumbs/custom/P/papas-burgeria.webp',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Burger.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Grill patties, stack burgers, and satisfy customers in one of the earliest Papa Louie classics.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-cheeseria',
  name: "Papa's Cheeseria",
  icon: '🧀',
  cover: 'https://www.y9freegames.com/wp-content/uploads/thumbs/custom/P/Papas-Cheeseria.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Cheese.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Craft grilled cheese sandwiches, fry sides, and keep customers happy in this cheesy fan favorite.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-cupcakeria',
  name: "Papa's Cupcakeria",
  icon: '🧁',
  cover: 'https://cdn.reludi.com/media/games/cqrsawje3lac.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Cupcake.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Bake, frost, and decorate cupcakes while juggling customer orders and seasonal holidays.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-donuteria',
  name: "Papa's Donuteria",
  icon: '🍩',
  cover: 'https://img.poki-cdn.com/cdn-cgi/image/q=78,scq=50,width=1200,height=1200,fit=cover,f=png/ac42fc62543c257861731ffbf401bf75/papas-donuteria.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Donut.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Fry, fill, and decorate donuts for a theme‑park crowd with fast‑paced multitasking.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-freezeria',
  name: "Papa's Freezeria",
  icon: '🍨',
  cover: 'https://gogamego.io/wp-content/uploads/thumbs/custom/P/papas-freezeria.webp',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Freeze.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Blend sundaes, add toppings, and serve customers on a relaxing tropical island.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-hot-doggeria',
  name: "Papa's Hot Doggeria",
  icon: '🌭',
  cover: 'https://all-papasgames.com/storage/images/games/papas-hot-doggeria/hd300jpg.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/HotDog.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Serve hot dogs, popcorn, and drinks to hungry fans at a bustling baseball stadium.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-pancakeria',
  name: "Papa's Pancakeria",
  icon: '🥞',
  cover: 'https://img.poki-cdn.com/cdn-cgi/image/quality=78,width=1200,height=1200,fit=cover,f=png/29ee26d83d0e533f31629e8195e9b1db.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Pancake.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Stack pancakes, waffles, and French toast with toppings in this breakfast‑themed entry.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-pastaria',
  name: "Papa's Pastaria",
  icon: '🍝',
  cover: 'https://img.poki-cdn.com/cdn-cgi/image/q=78,scq=50,width=1200,height=1200,fit=cover,f=png/b412fa2255f0dd1098b6759f71824cd7/papas-pastaria.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Pasta.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Boil pasta, prepare sauces, and bake breadsticks while managing a busy Italian restaurant.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-pizzeria',
  name: "Papa's Pizzeria",
  icon: '🍕',
  cover: 'https://imgr2.ant.games/games/papas-pizzeria/s600x600.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Pizza.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Take orders, top pizzas, bake them perfectly, and slice with precision in the original Papa’s game.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-scooperia',
  name: "Papa's Scooperia",
  icon: '🍪',
  cover: 'https://img.poki-cdn.com/cdn-cgi/image/q=78,scq=50,width=1200,height=1200,fit=cover,f=png/7da94623f93b04e8cf801e6a0803fb76/papas-scooperia.png',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Scoop.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Bake cookies, scoop ice cream, and build towering desserts for picky customers.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-sushiria',
  name: "Papa's Sushiria",
  icon: '🍣',
  cover: 'https://gogamego.io/wp-content/uploads/thumbs/custom/P/papas-sushiria.webp',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Sushi.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Roll sushi, prepare tea, and serve customers in one of the most complex Papa Louie games.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-taco-mia',
  name: "Papa's Taco Mia",
  icon: '🌮',
  cover: 'https://kbhgames.com/wp-content/uploads/2011/05/Papas-Taco-Mia.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Taco.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Grill meats, build tacos, and keep customers satisfied with fast service and accuracy.',
    featured: false,
  source: 'Community',
},

{
  id: 'community-papas-wingeria',
  name: "Papa's Wingeria",
  icon: '🍗',
  cover: 'https://poki.us.org/wp-content/uploads/2025/08/papas-wingeria.jpg',
  url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@main/Games/.Collections/Papaeria/Wing.html',
  category: 'Arcade',
  author: 'Flipline Studios',
  description: 'Fry wings, toss sauces, and plate sides in this fast‑paced chicken‑wing restaurant.',
    featured: false,
  source: 'Community',
},

  {
    id: 'gnmath-drive-mad',
    name: 'Drive Mad',
    icon: '🚗',
    cover: 'https://cdn.jsdelivr.net/gh/freebuisness/covers@main/35.png',
    url: 'https://cdn.jsdelivr.net/gh/gn-math/html@main/35.html',
    category: 'Arcade',
    author: 'Martin Magni',
    description: 'A physics-based driving game where you navigate increasingly tricky obstacle courses without flipping your vehicle. Simple controls hide fiendishly difficult levels that demand precision and patience.',
    featured: false,
    source: 'GN-Math',
  },

  {
    id: 'gnmath-slope',
    name: 'Slope',
    icon: '🟩',
    cover: 'https://cdn.jsdelivr.net/gh/freebuisness/covers@main/198.png',
    url: 'https://cdn.jsdelivr.net/gh/gn-math/html@main/198.html',
    category: 'Arcade',
    author: 'Y8 / RobKay',
    description: 'A fast, reflex-based downhill runner where you guide a ball through a neon 3D course. Speed increases constantly as obstacles, gaps, and sharp turns demand precise movement and quick reactions.',
    featured: false,
    source: 'GN-Math',
  },
];