// Game entries for ServerplexOS Games app
// Source: Eaglercraft / Minecraft browser clients
// All hosted on GitHub, served via jsDelivr CDN

var MINECRAFT_CLIENTS = [
  // ── Vanilla clients ──
  {
    id: 'mc-eaglercraft-152',
    name: 'Eaglercraft 1.5.2',
    icon: '⛏️',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/3khogames/3kh0@main/unblocked/eaglercraft.html',
    category: 'Minecraft',
    author: 'lax1dude',
    description: 'The original Eaglercraft — Minecraft 1.5.2 running entirely in your browser. Supports singleplayer worlds and multiplayer via WebSocket servers.',
    featured: true,
    source: 'MinecraftClients',
  },
  {
    id: 'mc-eaglercraft-188',
    name: 'Eaglercraft 1.8.8',
    icon: '⛏️',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/M/MinecraftClassic.html',
    category: 'Minecraft',
    author: 'lax1dude',
    description: 'Minecraft 1.8.8 in the browser. Full singleplayer with world saves, and multiplayer support through EaglerCraft-compatible servers.',
    featured: true,
    source: 'MinecraftClients',
  },
  {
    id: 'mc-eaglercraft-1122',
    name: 'Eaglercraft 1.12.2',
    icon: '⛏️',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/3khogames/3kh0@main/unblocked/eaglercraft1122.html',
    category: 'Minecraft',
    author: 'lax1dude',
    description: 'The latest major Eaglercraft version — Minecraft 1.12.2 with full singleplayer, advancements, shaders support, and EaglerCraft multiplayer.',
    featured: true,
    source: 'MinecraftClients',
  },
  {
    id: 'mc-minecraft-classic',
    name: 'Minecraft Classic',
    icon: '🧱',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/Serverplex/ServerplexOS-Games@master/Games/M/MinecraftClassic.html',
    category: 'Minecraft',
    author: 'Mojang',
    description: 'The original 2009 free version of Minecraft, officially playable in your browser. 32 blocks, creative building, and up to 9 players online.',
    featured: false,
    source: 'MinecraftClients',
  },

  // ── Hacked / modded clients (1.8) ──
  {
    id: 'mc-shadow-client',
    name: 'Shadow Client',
    icon: '🌑',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/Cristianboy9/EaglerClients.github.io@main/Shadow-Client.html',
    category: 'Minecraft',
    author: 'Shadow Team',
    description: 'A popular Eaglercraft 1.8 hacked client with modules like KillAura, ESP, Fly, and more. Includes a clean GUI for toggling cheats.',
    featured: false,
    source: 'MinecraftClients',
  },
  {
    id: 'mc-resent-client',
    name: 'Resent Client',
    icon: '⚡',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/Cristianboy9/EaglerClients.github.io@main/Resent-Signed.html',
    category: 'Minecraft',
    author: 'Resent Team',
    description: 'A feature-rich Eaglercraft 1.8 client with a large module list, clickGUI, and a slick dark-themed interface.',
    featured: false,
    source: 'MinecraftClients',
  },
  {
    id: 'mc-piclient',
    name: 'PiClient',
    icon: '🥧',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/Cristianboy9/EaglerClients.github.io@main/PiClient-v1.html',
    category: 'Minecraft',
    author: 'Pi Dev',
    description: 'A lightweight Eaglercraft 1.8 hacked client with essential modules and minimal performance overhead.',
    featured: false,
    source: 'MinecraftClients',
  },
  {
    id: 'mc-uwu-client',
    name: 'UwU Client',
    icon: '🌸',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/Cristianboy9/EaglerClients.github.io@main/UwU-client-b2-offline.html',
    category: 'Minecraft',
    author: 'UwU Dev',
    description: 'An Eaglercraft 1.8 client with a unique pastel-themed interface and a solid selection of hack modules.',
    featured: false,
    source: 'MinecraftClients',
  },
  {
    id: 'mc-premium-dragon',
    name: 'Premium Dragon',
    icon: '🐉',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/Cristianboy9/EaglerClients.github.io@main/PremiumDragonv2.html',
    category: 'Minecraft',
    author: 'Dragon Dev',
    description: 'A powerful Eaglercraft 1.8 hacked client with an expansive module list and a polished dragon-themed GUI.',
    featured: false,
    source: 'MinecraftClients',
  },

  // ── 1.12.2 hacked clients ──
  {
    id: 'mc-tuffclient-1122',
    name: 'Tuff Client 1.12.2',
    icon: '🪨',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/3khogames/3kh0@main/unblocked/tuff-client.html',
    category: 'Minecraft',
    author: 'Tuff Team',
    description: 'One of the most popular Eaglercraft 1.12.2 hacked clients. Packed with modules, a sleek GUI, and regular updates.',
    featured: true,
    source: 'MinecraftClients',
  },
  {
    id: 'mc-wurst-1122',
    name: 'Wurst Client 1.12.2',
    icon: '🌭',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/3khogames/3kh0@main/unblocked/wurst.html',
    category: 'Minecraft',
    author: 'Alexander01998',
    description: 'The legendary Wurst hacked client ported to Eaglercraft 1.12.2. 100+ mods, AutoFarm, Killaura, X-Ray, and much more.',
    featured: true,
    source: 'MinecraftClients',
  },
  {
    id: 'mc-precision-1122',
    name: 'Precision Client',
    icon: '🎯',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/3khogames/3kh0@main/unblocked/precision.html',
    category: 'Minecraft',
    author: 'Precision Team',
    description: 'A precise, performance-focused Eaglercraft 1.12.2 hacked client. Clean UI, solid module list, and smooth gameplay.',
    featured: false,
    source: 'MinecraftClients',
  },
  {
    id: 'mc-zenith-1122',
    name: 'Zenith Client',
    icon: '🔮',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/3khogames/3kh0@main/unblocked/zenith.html',
    category: 'Minecraft',
    author: 'Zenith Team',
    description: 'A sleek Eaglercraft 1.12.2 client with a modern GUI, customizable modules, and strong PvP-focused features.',
    featured: false,
    source: 'MinecraftClients',
  },
  {
    id: 'mc-astra-1122',
    name: 'Astra Client',
    icon: '🌟',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/3khogames/3kh0@main/unblocked/astra.html',
    category: 'Minecraft',
    author: 'Astra Team',
    description: 'Eaglercraft 1.12.2 client with a cosmic-themed interface and a broad set of modules for both PvP and utility.',
    featured: false,
    source: 'MinecraftClients',
  },
  {
    id: 'mc-eaglerforge',
    name: 'EaglerForge',
    icon: '🔧',
    cover: '',
    url: 'https://cdn.jsdelivr.net/gh/3khogames/3kh0@main/unblocked/eaglerforge.html',
    category: 'Minecraft',
    author: 'EaglerForge Team',
    description: 'A Forge-like modding platform for Eaglercraft 1.12.2. Load mods and customizations directly in your browser.',
    featured: true,
    source: 'MinecraftClients',
  },
];