// Game entries for ServerplexOS Games app
  // Source: Radon-Games (Radon-Games/Radon-Games)
  // Generated automatically - do not edit manually
  
var RADON_GAMES = [
  {
      id: 'radon-2048',
      name: '2048',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/2048',
      category: 'Puzzle',
      author: 'Gabriele Cirulli',
      description: 'Swipe to move the tiles, when two tiles with the same number touch, they merge into one. When a 2048 tile is created, the player wins.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-agario-minigame',
      name: 'Agario Minigame',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/agario-minigame',
      category: 'Arcade',
      author: 'Matheus Valadares',
      description: 'Agario is a fun addicting MMO game in which you have to eat or be eaten while you strive to dominate the World of colorful cells. The game has just 2 simple rules to follow: 1) you only can consume targets that are smaller than you and you should match their color to evolve yourself, 2) you must give larger objects a wide berth or you will die. Start moving through the grid and try to catch all the tiny blurs of color. Eat and grow, split and multiply and rule the world.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-astray',
      name: 'Astray',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/astray',
      category: 'Adventure',
      author: 'Aegon Games Ltd',
      description: 'Astray is a first-person horror/puzzle game set in an abandoned museum based on unusual cultures, legends, and supernatural themes; but something more sinister lurks beneath the surface.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-break-lock',
      name: 'Break Lock',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/break-lock',
      category: 'Puzzle',
      author: 'maxwellito',
      description: 'A hybrid of Mastermind and the Android pattern lock. A game you will love to hate. Empty circle means correct location but wrong order. Full circle means correct location in correct order. You are aiming for four full circles.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-the-chroma-incident',
      name: 'The Chroma Incident',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/the-chroma-incident',
      category: 'Shooter',
      author: 'Rybar',
      description: "The Achromats have taken the worlds color offline! Raid their colorless lair and vanquish them all, restoring the world to it's technicolor glory. A twin-stick shooter playable with gamepad or keyboard+mouse. Huge thanks to Herebefrogs for naming the game!",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-cookie-clicker',
      name: 'Cookie Clicker',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/cookie-clicker',
      category: 'Idle',
      author: 'Julien Orteil',
      description: 'Cookie Clicker is an incremental game created by French programmer Julien Orteil Thiennot in 2013. The user initially clicks on a big cookie on the screen, earning a single cookie per click.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-cube-field',
      name: 'Cube Field',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/cube-field',
      category: 'Arcade',
      author: 'YoArcade',
      description: "Cubefield is a simple but addictive game, there are only two controls - left and right. Use the arrow keys on your keyboard to guide your ship through an endless field of ominous looking coloured cubes - if you hit one, it's game over.",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-dinosaur',
      name: 'Dinosaur',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/dinosaur',
      category: 'Arcade',
      author: 'Chrome UX Team',
      description: 'The Dinosaur Game is a browser game developed by Google and built into the Google Chrome web browser. The player guides a pixelated Tyrannosaurus rex across a side-scrolling landscape, avoiding obstacles to achieve a higher score.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-doodle-jump',
      name: 'Doodle Jump',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/doodle-jump',
      category: 'Platformer',
      author: 'Croatian studio',
      description: 'How high can you go? A fun and simple game about an alien with a jetpack trying to jump as high as possible',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-fireboy-and-watergirl-forest-temple',
      name: 'Fireboy and Watergirl Forest Temple',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/fireboy-and-watergirl-forest-temple',
      category: 'Adventure',
      author: 'Oslo Albet',
      description: 'Help Fireboy and Watergirl through the forest temple tunnels and reach the exit doors in this fun arcade platform!',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-flappy-2048',
      name: 'Flappy 2048',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/flappy-2048',
      category: 'Puzzle',
      author: 'Abbasinasab',
      description: 'Jump through the tiles and get to 2048!',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-flappy-bird',
      name: 'Flappy Bird',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/flappy-bird',
      category: 'Arcade',
      author: 'Dong Nguyen',
      description: 'Flappy Bird is a mobile game developed by Vietnamese video game artist and programmer Dong Nguyen, under his game development company .Gears. The game is a side-scroller where the player controls a bird, attempting to fly between columns of green pipes without hitting them.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-friendly-fire',
      name: 'Friendly Fire',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/friendly-fire',
      category: 'Platformer',
      author: 'Eduard But, Benjamin Jung, Markus Over, Matthias Wetter, Nico Hülscher, Nils Kreutzer, Ranjit Mevius, and Klaus Reimer',
      description: 'Friendly Fire is a 2d platform adventure game with handcrafted pixel art, an original soundtrack and lots of love put into the creation of the characters and dialogues.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-geometry-dash',
      name: 'Geometry Dash',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/geometry-dash',
      category: 'Rhythm',
      author: 'griffpatch',
      description: 'Geometry Dash is developed by Sweden-based developer Robert Topala. The game has 21 levels currently with different types of difficulty. Players can enjoy 3 levels of the game: Stereo Madness, Back on track, and Polargeist. Each one has its own difficulty and a list of best scores.',
      featured: true,
      source: 'Radon-Games',
    },

  {
      id: 'radon-gopher-kart',
      name: 'Gopher Kart',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/gopher-kart',
      category: 'Driving',
      author: 'Jamilet Zelaya',
      description: 'Created by Jamilet Zelaya with very little help from Erick Zelaya.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-hexgl',
      name: 'HexGL',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/hexgl',
      category: 'Driving',
      author: 'Thibaut Despoulain',
      description: 'HexGL is a futuristic, fast-paced racing game built by Thibaut Despoulain using HTML5, Javascript and WebGL and a tribute to the original Wipeout and F-Zero series.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-hextris',
      name: 'Hextris',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/hextris',
      category: 'Puzzle',
      author: 'Logan Engstrom',
      description: 'An addictive puzzle game inspired by Tetris.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-minecraft',
      name: 'Minecraft',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/minecraft',
      category: 'Adventure',
      author: 'Markus Persson',
      description: "Minecraft is a video game in which players create and break apart various kinds of blocks in three-dimensional worlds. The game's two main modes are Survival and Creative. In Survival, players must find their own building supplies and food. They also interact with blocklike mobs, or moving creatures.",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-microsoft-flight-simulator',
      name: 'Microsoft Flight Simulator',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/microsoft-flight-simulator',
      category: 'Arcade',
      author: 'Microsoft',
      description: 'Microsoft Flight Simulator is a series of amateur flight simulator programs for Microsoft Windows operating systems, and earlier for MS-DOS and Classic Mac OS. It is one of the longest-running, best-known, and most comprehensive home flight simulator programs on the market.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-pacman-html',
      name: 'Pacman',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/pacman-html',
      category: 'Arcade',
      author: 'Bandai Namco Entertainment',
      description: 'Pac-Man is a Japanese video game franchise published, developed and owned by Bandai Namco Entertainment. Entries have been developed by a wide array of other video game companies, including Midway Games, Atari and Mass Media, Inc..',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-radius-raid',
      name: 'Radius Raid',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/radius-raid',
      category: 'Shooter',
      author: 'Jack Rugile',
      description: "Radius Raid is a space themed shoot 'em up where you must blast away unrelenting enemies before they destroy you. The game features 13 enemy types, 5 powerups, parallax backgrounds, retro sound effects, and locally stored stats.",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-retro-bowl',
      name: 'Retro Bowl',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/retro-bowl',
      category: 'Sports',
      author: 'New Star Games',
      description: 'Retro Bowl is an American football video game developed by New Star Games for the iOS and Android operating systems. A browser version is also available on some websites. The game was released in January 2020 and due to its exposure on the website TikTok it massively increased in popularity in late 2021.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-run-3',
      name: 'Run 3',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/run-3',
      category: 'Skill',
      author: 'Joseph Cloutier',
      description: 'Run 3 is an exciting running game where you run, jump through an endless tunnel in space. Pass all challenges of hundred levels without falling into space.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-sm64',
      name: 'Super Mario 64',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/sm64',
      category: 'Platformer',
      author: 'Nintendo',
      description: 'Super Mario 64 is a 1996 platform game for the Nintendo 64, developed by Nintendo EAD and published by Nintendo. The first Super Mario game to feature 3D gameplay, it features freedom of movement within a large open world based on polygons, combined with traditional Mario gameplay, visual style, and characters.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-space-invaders',
      name: 'Space Invaders',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/space-invaders',
      category: 'Arcade',
      author: 'Taito',
      description: 'Space Invaders is a Japanese shooting video game released in 1978 by Taito. It was developed by Tomohiro Nishikado, who was inspired by other media: Breakout, The War of the Worlds, and Star Wars.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-tank-trouble',
      name: 'Tank Trouble',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/tank-trouble',
      category: 'Action',
      author: 'Mads Purup',
      description: 'Tank Trouble is an online tank game where you drive in a maze and shoot missiles at your enemies. Tank Trouble pits you against clever army generals in mazelike battlefields. In Solo mode, you will face Laika, a master of war. You can also challenge a friend or two in multiplayer warfare.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-vex-3',
      name: 'Vex 3',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/vex-3',
      category: 'Action',
      author: 'Amazing Adam',
      description: 'Vex 3 is a fascinating game. Your task is to Take Vex through the levels by running, jumping, sliding and swimming while avoiding dangerous obstacles.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-vex-4',
      name: 'Vex 4',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/vex-4',
      category: 'Action',
      author: 'Amazing Adam',
      description: 'VEX 4 takes Vex to the next level! This fast paced stickman game puts your skills to the test. Run, jump, slide, swim and avoid obstacles, VEX 4 has it all.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-vex-5',
      name: 'Vex 5',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/vex-5',
      category: 'Action',
      author: 'Amazing Adam',
      description: "Surely you are very familiar to the Vex game series. Now, you can meet cute Stickman again in Vex 5. Vex 5 is the 5th platform game in the Vex series. Each level is a labyrinth of deadly devices and traps. You have to make your way from one platform to the other and avoid deadly obstacles such as buzzsaws, spikes, crumbling blocks, and more! To win this game, you must overcome dangerous spikes, saw blades, and a variety of other challenges. If you've played the previous games in the series, you'll be familiar with what to expect in this thrilling new installment. The goal is to finish each level by reaching the endpoint. In this game, levels are referred to as acts, and there are numerous acts to finish.",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-vex-6',
      name: 'Vex 6',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/vex-6',
      category: 'Action',
      author: 'Amazing Adam',
      description: 'Vex 6 is an awesome online game where you need to make an exceptional effort to pass all obstacles including cannons, spinning spikes, razors, and others to succeed.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-rolling-sky',
      name: 'Rolling Sky',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/rolling-sky',
      category: 'Platformer',
      author: 'Cheetah Games',
      description: 'Rolling Sky is the best musical skill game of all time. You are a ball rolling over a track with tons of hazards to make you fall. You have to be super fast, precise and accurate to dodge all the barriers, holes and laser beams that are shot in your direction. Use the music to keep your rhythm while swinging from left to right to get the power-ups you need to finish the levels. This is seriously the most challenging game you can find online.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-bike-mania',
      name: 'Bike Mania',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/bike-mania',
      category: 'Sports',
      author: 'Ace Viral',
      description: 'Ride your bike through the bumpy and challenging tracks. Do not hit the ground and show your skill! Release Date. April 2007 (Flash). January 2020 (HTML5).',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-moto-x3m',
      name: 'Moto X3M',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/moto-x3m',
      category: 'Driving',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-moto-x3m-winter',
      name: 'Moto X3M Winter',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/moto-x3m-winter',
      category: 'Driving',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-moto-x3m-spooky-land',
      name: 'Moto X3M Spooky Land',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/moto-x3m-spooky-land',
      category: 'Driving',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-moto-x3m-pool-party',
      name: 'Moto X3M Pool Party',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/moto-x3m-pool-party',
      category: 'Driving',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-hill-racing',
      name: 'Hill Racing',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/hill-racing',
      category: 'Driving',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-running-bot-xmas-gifts',
      name: 'Running Bot Xmas Gifts',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/running-bot-xmas-gifts',
      category: 'Skill',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-zombotron',
      name: 'Zombotron',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/zombotron',
      category: 'Zombie',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-zombotron-2',
      name: 'Zombotron 2',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/zombotron-2',
      category: 'Zombie',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-zombotron-2-time-machine',
      name: 'Zombotron 2 Time Machine',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/zombotron-2-time-machine',
      category: 'Zombie',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-donut-boy',
      name: 'Donut Boy',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/donut-boy',
      category: 'Indie',
      author: 'Damon',
      description: "The Dough-Nutter 4000 has malfunctioned! It's up to you, Donut Boy, to rescue the employees and donuts that were scattered around town from the resulting explosion.",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-wordle',
      name: 'Wordle',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/wordle',
      category: 'Strategy',
      author: 'Unknown',
      description: 'Wordle is a web-based word game developed by Welsh-born software engineer Josh Wardle. Players have six attempts to guess a five-letter word; feedback is given for each guess, in the form of colored tiles, indicating when letters match or occupy the correct position. This tweak has no limit to how many games you can play!',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-google-solitaire',
      name: 'Google Solitaire',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/google-solitaire',
      category: 'Google',
      author: 'Google',
      description: 'Patience, card solitaire or just solitaire, is a genre of card games that can be played by a single player. Patience games can also be played in a head-to-head fashion with the winner selected by a scoring scheme.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-a-dark-room',
      name: 'A Dark Room',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/a-dark-room',
      category: 'Arcade',
      author: 'Unknown',
      description: 'A Dark Room is a minimalist text-based adventure RPG game right in your browser! How far will you go, player?',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-align-4',
      name: 'Align 4',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/align-4',
      category: 'Arcade',
      author: 'Unknown',
      description: "Align 4 is a two-player connection board game just like Connect 4, in which the players choose a color and then take turns dropping colored discs into a seven-column, six-row vertically suspended grid. The pieces fall straight down, occupying the lowest available space within the column. The objective of the game is to be the first to form a horizontal, vertical, or diagonal line of four of one's own discs. The first player can always win by playing the right moves.",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-colorun',
      name: 'Colorun',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/colorun',
      category: 'Arcade',
      author: 'Unknown',
      description: "COLORON is a fun and well-designed platformer. The goal is to match the color of the tower to the bouncing ball. Keep it going for as long as you can, just don't get mad.",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-geometry-dash-remastered',
      name: 'Geometry Dash Remastered',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/geometry-dash-remastered',
      category: 'Arcade',
      author: 'Unknown',
      description: "Welcome all to Geometry Dash Remastered, and, well, you already know the game. But this is more, this is 5 new levels you can't find anywhere else, this is ... REMASTERED (I'm totally serious).",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-google-snake',
      name: 'Google Snake',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/google-snake',
      category: 'Google',
      author: 'Google',
      description: 'How long can you last before your tail becomes your dinner? Take the challenge and eat all those apples! Be careful not to hit the wall!',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-hacker-typer',
      name: 'Hacker Typer',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/hacker-typer',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-basket-random',
      name: 'Basket Random',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/basket-random',
      category: 'Sports',
      author: 'Unknown',
      description: 'The random series continues with Basket Random! Basketball is here with its most funny and random way. In Basket Random game, try to score a basket by using only one key with different variations from each other! Changing fields, changing players and changing balls do not surprise you! You can be the best of them all. You can play Basket Random game either against CPU or against a friend in 2 player gaming mode! The one who reaches 5 score first, wins the game. Have Fun!',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-basketball-stars',
      name: 'Basketball Stars',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/basketball-stars',
      category: 'Arcade',
      author: 'Unknown',
      description: 'Basketball Stars is a 2-player basketball game created by Madpuffers. You can play solo or with a friend as a variety of legendary basketball players. Shoot basketball with the likes of LeBron James, James Harden, and Stephen Curry in Basketball Stars!',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-minesweeper',
      name: 'Minesweeper',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/minesweeper',
      category: 'Arcade',
      author: 'Unknown',
      description: "Minesweeper is a single-player puzzle video game. The objective of the game is to clear a rectangular board containing hidden 'mines' or bombs without detonating any of them, with help from clues about the number of neighboring mines in each field.",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-sans-fight',
      name: 'Sans Fight',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/sans-fight',
      category: 'Arcade',
      author: 'Unknown',
      description: "Undertale Sans Fight Clone; 'do you wanna have a bad time? 'cause if you visit this page... you are REALLY not going to like what happens next.'",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-there-is-no-game',
      name: 'There is no Game',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/there-is-no-game',
      category: 'Arcade',
      author: 'Unknown',
      description: 'There is no game. There is nothing to do. Do not click or tap anywhere. Really. DO NOT CLICK OR TAP ANYWHERE. Do not laugh as there is nothing to laugh about.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-unfair-dyne',
      name: 'Unfair Dyne',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/unfair-dyne',
      category: 'Arcade',
      author: 'Unknown',
      description: "Break the word in half and add 'UN' to each part. Undyne fight, but harder.",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-soccer-random',
      name: 'Soccer Random',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/soccer-random',
      category: 'Sports',
      author: 'Unknown',
      description: "Soccer Random is one of the most fun sports games. The game's objective is to score a goal using only one key with different variations!",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-volley-random',
      name: 'Volley Random',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/volley-random',
      category: 'Sports',
      author: 'Unknown',
      description: 'The fun random game series continues with Volley Random. There is a Volleyball experience unlike any before. With fun ragdoll physics and a variety of variations, each match will be different. The playing court, ball and players may change. The important thing is to be able to get score under all conditions. ',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-boxing-random',
      name: 'Boxing Random',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/boxing-random',
      category: 'Sports',
      author: 'Unknown',
      description: "The new version of the random game series that you love to play continues with Boxing Random. Again, changing conditions occur in every round. Sometimes the boxing field changes and sometimes the boxers. Adapt to every random feature and hit accurately. When you get the rocket punch, balance and send it to the opponent's head. This way you can knock out the opponent without getting close! The one who reaches 5 score first, wins the game!",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-uno',
      name: 'Uno',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/uno',
      category: 'Arcade',
      author: 'Unknown',
      description: 'The classic popular game UNO can be played online in the browser. You can play the game locally or online multiplayer. You can enter the lobbies in the online section. Face up to 3 CPU-controlled opponents. Match cards by color or number, play action cards to mix the game up and be the first to get rid of all cards. Also, do not forget to press the 1 button when you have only one card left!',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-flakboy',
      name: 'Flakboy',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/flakboy',
      category: 'Arcade',
      author: 'Unknown',
      description: "Wanna try out some awesome new weapons? Of course you do. Get blastin'!",
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-gun-knight',
      name: 'Gun Knight',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/gun-knight',
      category: 'Arcade',
      author: 'Evan Samuel',
      description: 'A roguelike heavily inspired by Gungeon and Binding of Isaac, you play a Knight whose quest is to venture into a nearby dungeon.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-celeste',
      name: 'Celeste',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/celeste',
      category: 'Arcade',
      author: 'Matt Thorson',
      description: 'Celeste is a 2018 platform game developed and published by indie studio Maddy Makes Games. The player controls Madeline, a young woman with anxiety and depression who aims to climb Celeste Mountain. During her climb, she encounters several characters, including a personification of her self-doubt known as Badeline, who attempts to stop her from climbing the mountain.',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-fire-truck-dash',
      name: 'Fire Truck Dash',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/fire-truck-dash',
      category: 'Driving',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'Radon-Games',
    },

  {
      id: 'radon-google-gnome',
      name: 'Google Gnome',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/Radon-Games/Radon-Games@main/public/games/google-gnome',
      category: 'Google',
      author: 'Google',
      description: 'Use your trusty catapult (or trebuchet to be precise) to launch your clay gnomes into the farthest reaches of your garden. The farther your gnome travels, the more flowers you plant the more points you earn!',
      featured: false,
      source: 'Radon-Games',
    },
];