// Game entries for ServerplexOS Games app
  // Source: TobiasMue91 (TobiasMue91/tobiasmue91.github.io)
  // Generated automatically — do not edit manually
  
var TOBIAS_GAMES = [
  {
      id: 'tobias-2048',
      name: '2048',
      icon: '🔢',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/2048.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: true,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-8-ball',
      name: '8-Ball',
      icon: '🎱',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/8-ball.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-agario',
      name: 'Agario',
      icon: '🧬',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/agario.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-alphabet',
      name: 'Alphabet',
      icon: '🔤',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/alphabet.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-animals',
      name: 'Animals',
      icon: '🐻',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/animals.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-artillery',
      name: 'Artillery',
      icon: '💥',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/artillery.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-asteroids',
      name: 'Asteroids',
      icon: '🚀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/asteroids.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-asteroids_3d',
      name: 'Asteroids 3d',
      icon: '🚀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/asteroids_3d.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-backgammon',
      name: 'Backgammon',
      icon: '🎲',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/backgammon.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-ball_bouncing',
      name: 'Ball Bouncing',
      icon: '😀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/ball_bouncing.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-blackjack',
      name: 'Blackjack',
      icon: '🃏',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/blackjack.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-blockdrop',
      name: 'Blockdrop',
      icon: '🧱',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/blockdrop.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-breakout',
      name: 'Breakout',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/breakout.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-catchcircle',
      name: 'Catchcircle',
      icon: '🪤',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/catchcircle.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-chain_reaction',
      name: 'Chain Reaction',
      icon: '⛓️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/chain_reaction.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-checkers',
      name: 'Checkers',
      icon: '⚪',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/checkers.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-chess',
      name: 'Chess',
      icon: '♟️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/chess.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-color_flood',
      name: 'Color Flood',
      icon: '🎨',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/color_flood.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-color_guessing_game',
      name: 'Color Guessing Game',
      icon: '🎨',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/color_guessing_game.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-connect_four',
      name: 'Connect Four',
      icon: '🔗',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/connect_four.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-crazy_eights',
      name: 'Crazy Eights',
      icon: '🤪',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/crazy_eights.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-death_by_ai',
      name: 'Death By Ai',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/death_by_ai.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-deep_miner',
      name: 'Deep Miner',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/deep_miner.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-doodling',
      name: 'Doodling',
      icon: '🎨',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/doodling.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-duck_hunt',
      name: 'Duck Hunt',
      icon: '🦆',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/duck_hunt.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-emoji_horde',
      name: 'Emoji Horde',
      icon: '😀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/emoji_horde.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-emoji_horde_survival',
      name: 'Emoji Horde Survival',
      icon: '😀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/emoji_horde_survival.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-emoji_match_three',
      name: 'Emoji Match Three',
      icon: '😀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/emoji_match_three.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-emoji_puzzle_mania',
      name: 'Emoji Puzzle Mania',
      icon: '😀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/emoji_puzzle_mania.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-escape_the_maze',
      name: 'Escape The Maze',
      icon: '🚪',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/escape_the_maze.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-family_feud',
      name: 'Family Feud',
      icon: '👨‍👩‍👧‍👦',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/family_feud.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-fathom',
      name: 'Fathom',
      icon: '🐋',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/fathom.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-fishing',
      name: 'Fishing',
      icon: '🎣',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/fishing.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-flappy_bird',
      name: 'Flappy Bird',
      icon: '🐦',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/flappy_bird.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-fling',
      name: 'Fling',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/fling.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-freecell',
      name: 'Freecell',
      icon: '🃏',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/freecell.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-frogger',
      name: 'Frogger',
      icon: '🐸',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/frogger.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-hangman',
      name: 'Hangman',
      icon: '📝',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/hangman.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-human_benchmark',
      name: 'Human Benchmark',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/human_benchmark.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-idle_factory',
      name: 'Idle Factory',
      icon: '💤',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/idle_factory.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-interactive_buddy',
      name: 'Interactive Buddy',
      icon: '👥',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/interactive_buddy.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-jigsaw',
      name: 'Jigsaw',
      icon: '🖼️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/jigsaw.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-jump',
      name: 'Jump',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/jump.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-lights_out',
      name: 'Lights Out',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/lights_out.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-living_rps',
      name: 'Living Rps',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/living_rps.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-ludo',
      name: 'Ludo',
      icon: '🎲',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/ludo.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-memory_match',
      name: 'Memory Match',
      icon: '🧠',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/memory_match.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-minesweeper',
      name: 'Minesweeper',
      icon: '💣',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/minesweeper.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-mini_tower_defense',
      name: 'Mini Tower Defense',
      icon: '🏗️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/mini_tower_defense.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-missile_command',
      name: 'Missile Command',
      icon: '💥',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/missile_command.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-monkeytype',
      name: 'Monkeytype',
      icon: '🐵',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/monkeytype.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-mystery_ai',
      name: 'Mystery Ai',
      icon: '🕵️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/mystery_ai.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-nonogram',
      name: 'Nonogram',
      icon: '📐',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/nonogram.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-number_guess',
      name: 'Number Guess',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/number_guess.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-number_guess_gpt_4',
      name: 'Number Guess Gpt 4',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/number_guess_gpt_4.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-obstacle_dodge',
      name: 'Obstacle Dodge',
      icon: '🚧',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/obstacle_dodge.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-pong',
      name: 'Pong',
      icon: '🏓',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/pong.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-push_mine',
      name: 'Push Mine',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/push_mine.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-qix',
      name: 'Qix',
      icon: '🐍',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/qix.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-reversi',
      name: 'Reversi',
      icon: '⚪',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/reversi.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-rock_paper_scissors',
      name: 'Rock Paper Scissors',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/rock_paper_scissors.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-rock_paper_scissors_mp',
      name: 'Rock Paper Scissors Mp',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/rock_paper_scissors_mp.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-rubiks_cube',
      name: 'Rubiks Cube',
      icon: '🧩',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/rubiks_cube.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-simon_says',
      name: 'Simon Says',
      icon: '🎵',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/simon_says.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-snake',
      name: 'Snake',
      icon: '🐍',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/snake.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-solitaire',
      name: 'Solitaire',
      icon: '🃏',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/solitaire.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-space_invaders',
      name: 'Space Invaders',
      icon: '🚀',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/space_invaders.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-stack_tower',
      name: 'Stack Tower',
      icon: '🏗️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/stack_tower.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-sudoku',
      name: 'Sudoku',
      icon: '📐',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/sudoku.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-suika',
      name: 'Suika',
      icon: '🍒',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/suika.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-tic_tac_toe_mp',
      name: 'Tic Tac Toe Mp',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/tic_tac_toe_mp.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-time_travel_agency',
      name: 'Time Travel Agency',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/time_travel_agency.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-tower_of_hanoi',
      name: 'Tower Of Hanoi',
      icon: '🏗️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/tower_of_hanoi.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-two_truths_one_lie',
      name: 'Two Truths One Lie',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/two_truths_one_lie.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-typing_game',
      name: 'Typing Game',
      icon: '⌨️',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/typing_game.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-void',
      name: 'Void',
      icon: '💫',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/void.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-void_runner',
      name: 'Void Runner',
      icon: '💫',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/void_runner.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-webcraft',
      name: 'Webcraft',
      icon: '🎨',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/webcraft.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-whac',
      name: 'Whac',
      icon: '🐻',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/whac.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-who_wants_to_be_a_millionaire',
      name: 'Who Wants To Be A Millionaire',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/who_wants_to_be_a_millionaire.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-wordle',
      name: 'Wordle',
      icon: '🔤',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/wordle.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-word_rain',
      name: 'Word Rain',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/word_rain.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-word_search',
      name: 'Word Search',
      icon: '🎮',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/word_search.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },

  {
      id: 'tobias-yahtzee',
      name: 'Yahtzee',
      icon: '🎲',
      cover: '',
      url: 'https://cdn.jsdelivr.net/gh/TobiasMue91/tobiasmue91.github.io@main/games/yahtzee.html',
      category: 'Arcade',
      author: 'Unknown',
      description: '',
      featured: false,
      source: 'TobiasMue91',
    },
];